-- CI-only historical schema contract.
--
-- The production project predates the migration files currently committed in
-- this repository. This fixture models the tables/functions that must exist
-- before the administrative and platform-hardening migrations are replayed.
-- It is never pushed to Supabase and does not replace the exact production
-- baseline that must eventually be captured with `supabase db pull`.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
    id uuid primary key,
    full_name text,
    phone text,
    role text not null default 'passenger',
    status text not null default 'offline',
    avatar_url text,
    vehicle_type text,
    vehicle_brand text,
    vehicle_model text,
    vehicle_color text,
    license_plate text,
    payment_qr_url text,
    curr_lat double precision,
    curr_lng double precision,
    last_location_update timestamptz,
    subscription_status text not null default 'suspended',
    last_payment_date timestamptz,
    suspended_at timestamptz,
    current_session_id text,
    fcm_token text,
    fcm_updated_at timestamptz,
    referral_code text,
    referral_credit_balance numeric(12,2) not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.rides (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete restrict,
    driver_id uuid references public.profiles(id) on delete set null,
    pickup text not null,
    dropoff text not null,
    price numeric(12,2) not null default 0,
    ride_type text not null default 'standard',
    status text not null default 'requested',
    payment_method text,
    payment_reference text,
    passenger_phone text,
    pickup_lat double precision,
    pickup_lng double precision,
    dropoff_lat double precision,
    dropoff_lng double precision,
    service_type text not null default 'ride',
    delivery_info jsonb,
    delivery_instructions text,
    payer text,
    cod_amount numeric(12,2),
    cod_currency text,
    cod_collected boolean not null default false,
    pickup_pod_url text,
    delivery_pod_url text,
    wait_seconds integer not null default 0,
    wait_fee numeric(12,2) not null default 0,
    payment_confirmed_by_user boolean not null default false,
    payment_confirmed_by_driver boolean not null default false,
    payment_confirmed_at timestamptz,
    arrived_at_dropoff_at timestamptz,
    cancellation_reason text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.payment_reports (
    id uuid primary key default gen_random_uuid(),
    driver_id uuid not null references public.profiles(id) on delete cascade,
    payment_type text,
    bank_origin text,
    reference_last6 text,
    sender_phone text,
    amount_reported numeric(14,2),
    amount_real numeric(14,2),
    trn_date date,
    banesco_status text,
    status text not null default 'pending',
    error_message text,
    raw_response jsonb,
    receipt_url text,
    created_at timestamptz not null default now()
);

create unique index if not exists uq_payment_reports_ref_validated
on public.payment_reports(bank_origin, reference_last6, trn_date)
where status = 'validated';

create table if not exists public.promo_codes (
    id bigint generated by default as identity primary key,
    code text not null unique,
    description text,
    discount_type text not null default 'percent',
    discount_value numeric(12,2) not null default 0,
    max_uses integer,
    used_count integer not null default 0,
    max_uses_per_user integer,
    min_ride_amount numeric(12,2) not null default 0,
    expires_at timestamptz,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.pricing_config (
    id bigint generated by default as identity primary key,
    vehicle_type text not null unique,
    base numeric(12,2) not null,
    per_km numeric(12,2) not null,
    delivery_fee numeric(12,2) not null default 0,
    wait_per_min numeric(12,2) not null default 0,
    stop_fee numeric(12,2) not null default 0,
    updated_at timestamptz not null default now()
);

insert into public.pricing_config(vehicle_type, base, per_km, delivery_fee, wait_per_min, stop_fee)
values
    ('moto', 1.00, 0.25, 0.50, 0.05, 0.50),
    ('standard', 1.50, 0.40, 1.50, 0.08, 1.00),
    ('van', 1.70, 0.60, 2.00, 0.10, 1.00)
on conflict (vehicle_type) do nothing;

create table if not exists public.pricing_rules (
    id bigint generated by default as identity primary key,
    active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.coverage_zones (
    id bigint generated by default as identity primary key,
    name text not null,
    center_lat double precision not null,
    center_lng double precision not null,
    radius_km double precision not null default 30,
    active boolean not null default true,
    created_at timestamptz not null default now()
);

insert into public.coverage_zones(name, center_lat, center_lng, radius_km)
values ('Higuerote', 10.4653, -65.9711, 35)
on conflict do nothing;

create or replace function public.is_within_coverage(
    p_lat double precision,
    p_lng double precision
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists(
        select 1
        from public.coverage_zones z
        where z.active
          and 2 * 6371 * asin(sqrt(
              power(sin(radians((z.center_lat - p_lat) / 2)), 2)
              + cos(radians(p_lat)) * cos(radians(z.center_lat))
              * power(sin(radians((z.center_lng - p_lng) / 2)), 2)
          )) <= z.radius_km
    );
$$;

grant execute on function public.is_within_coverage(double precision,double precision)
to authenticated;

create table if not exists public.support_threads (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references public.profiles(id) on delete cascade,
    role_context text,
    status text not null default 'open',
    unread_for_admin boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(user_id, role_context)
);

create table if not exists public.terms_acceptances (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    terms_kind text not null,
    terms_version text not null,
    accepted_at timestamptz not null default now(),
    ride_id bigint references public.rides(id) on delete cascade
);

create table if not exists public.membership_plans (
    plan text primary key,
    period text,
    amount_usd numeric(12,2),
    amount_bs numeric(14,2),
    bs_updated_at timestamptz,
    display_name text
);

create materialized view public.fraud_signals as
select
    null::text as subject_type,
    null::text as subject_id,
    null::text as signal,
    null::text as severity,
    '{}'::jsonb as metadata,
    now()::timestamptz as computed_at
where false;
