project_id = "higo-platform-ci"

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.seed]
enabled = false

[studio]
enabled = false

[inbucket]
enabled = false

[analytics]
enabled = false
