-- Create the rides table
create table public.rides (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  pickup text not null,
  dropoff text not null,
  price numeric not null,
  status text not null default 'requested'::text,
  payment_method text not null,
  driver_id uuid references auth.users
);

-- Enable Row Level Security (RLS)
alter table public.rides enable row level security;

-- Create Policy: Users can insert their own rides
create policy "Users can insert their own rides"
on public.rides for insert
to authenticated
with check (true);

-- Create Policy: Users can view their own rides
create policy "Users can view their own rides"
on public.rides for select
to authenticated
using (auth.uid() = user_id);

-- Create Policy: Drivers (or anyone for now, refine later) can view available rides
-- For simplicity in this demo, we allow authenticated users to see all rides if they have a 'driver' role or similar, 
-- but for now let's just allow users to see their own.
-- If you need drivers to see requested rides:
create policy "Drivers can view requested rides"
on public.rides for select
to authenticated
using (status = 'requested');
