-- Create messages table for Real-time Chat
create table public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  ride_id bigint references public.rides(id) not null,
  sender_id uuid references auth.users(id) not null,
  content text not null,
  is_read boolean default false
);

-- Enable RLS
alter table public.messages enable row level security;

-- Policies
create policy "Users can view messages for their rides"
on public.messages for select
to authenticated
using (
  exists (
    select 1 from public.rides
    where rides.id = messages.ride_id
    and (rides.user_id = auth.uid() or rides.driver_id = auth.uid())
  )
);

create policy "Users can insert messages for their rides"
on public.messages for insert
to authenticated
with check (
  exists (
    select 1 from public.rides
    where rides.id = messages.ride_id
    and (rides.user_id = auth.uid() or rides.driver_id = auth.uid())
  )
);
