-- ============================================================
-- 13 · Confirmación bilateral de pago + Sistema de membresías
-- ============================================================

-- ------------------------------------------------------------
-- A) PAGOS BILATERALES POR VIAJE
-- ------------------------------------------------------------
-- Se amplía la fila de rides con columnas que registran:
--   - El método que el pasajero usó para pagar.
--   - La referencia (nº de operación Pago Móvil, últimos 4 de Zelle, etc).
--   - Dos booleans que cada parte marca al confirmar el pago.
--   - Timestamp del cierre cuando ambos confirman.
ALTER TABLE public.rides
    ADD COLUMN IF NOT EXISTS payment_method TEXT DEFAULT 'pago_movil',
    ADD COLUMN IF NOT EXISTS payment_reference TEXT,
    ADD COLUMN IF NOT EXISTS payment_confirmed_by_user BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS payment_confirmed_by_driver BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS payment_confirmed_at TIMESTAMPTZ;

-- ------------------------------------------------------------
-- B) MEMBRESÍAS DE CONDUCTOR
-- ------------------------------------------------------------
-- Cada pago de flota crea una fila. La más reciente con expires_at > now()
-- define si el driver está activo.
CREATE TABLE IF NOT EXISTS public.driver_memberships (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id      UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    plan           TEXT NOT NULL CHECK (plan IN ('moto','standard','van')),
    amount         NUMERIC NOT NULL,
    period         TEXT NOT NULL DEFAULT 'monthly' CHECK (period IN ('weekly','monthly','yearly')),
    payment_method TEXT NOT NULL DEFAULT 'pago_movil',
    reference      TEXT,
    paid_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at     TIMESTAMPTZ NOT NULL,
    status         TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','expired','refunded')),
    notes          TEXT,
    created_at     TIMESTAMPTZ DEFAULT NOW(),
    created_by     UUID REFERENCES public.profiles(id)
);

CREATE INDEX IF NOT EXISTS idx_memberships_driver
    ON public.driver_memberships(driver_id, expires_at DESC);
CREATE INDEX IF NOT EXISTS idx_memberships_active_expires
    ON public.driver_memberships(expires_at)
    WHERE status = 'active';

ALTER TABLE public.driver_memberships ENABLE ROW LEVEL SECURITY;

-- El conductor ve sólo sus propias membresías.
DROP POLICY IF EXISTS "drivers_read_own_memberships" ON public.driver_memberships;
CREATE POLICY "drivers_read_own_memberships"
    ON public.driver_memberships FOR SELECT
    TO authenticated
    USING (driver_id = auth.uid());

-- Los admins pueden crear/editar/borrar cualquier membresía.
DROP POLICY IF EXISTS "admins_manage_memberships" ON public.driver_memberships;
CREATE POLICY "admins_manage_memberships"
    ON public.driver_memberships FOR ALL
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND role = 'admin'
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND role = 'admin'
        )
    );

-- ------------------------------------------------------------
-- C) HELPER: ¿el conductor tiene membresía activa?
-- ------------------------------------------------------------
-- SECURITY DEFINER para que funcione también desde el cliente sin
-- exponer el contenido de driver_memberships (sólo devuelve boolean).
CREATE OR REPLACE FUNCTION public.driver_has_active_membership(p_driver_id UUID)
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.driver_memberships
        WHERE driver_id = p_driver_id
          AND status = 'active'
          AND expires_at > NOW()
    );
$$;

GRANT EXECUTE ON FUNCTION public.driver_has_active_membership(UUID) TO authenticated;

-- ------------------------------------------------------------
-- D) SYNC AUTOMÁTICO: profiles.subscription_status ← memberships
-- ------------------------------------------------------------
-- Al insertar/actualizar una membresía, refresca el status del profile
-- para que el resto de la app (y los paneles) lo lea sin doble query.
CREATE OR REPLACE FUNCTION public.sync_driver_subscription_status()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    UPDATE public.profiles
       SET subscription_status = CASE
               WHEN public.driver_has_active_membership(NEW.driver_id) THEN 'active'
               ELSE 'suspended'
           END,
           last_payment_date = NEW.paid_at
     WHERE id = NEW.driver_id;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_subscription_status ON public.driver_memberships;
CREATE TRIGGER trg_sync_subscription_status
    AFTER INSERT OR UPDATE ON public.driver_memberships
    FOR EACH ROW
    EXECUTE FUNCTION public.sync_driver_subscription_status();
