-- ============================================================
-- 14 · Códigos promocionales + Sistema de referidos
-- ============================================================

-- ------------------------------------------------------------
-- A) PROMO CODES — descuentos genéricos (HIGUEROTE, etc.)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.promo_codes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            TEXT NOT NULL UNIQUE,
    description     TEXT,
    discount_type   TEXT NOT NULL CHECK (discount_type IN ('percent', 'fixed')),
    discount_value  NUMERIC NOT NULL CHECK (discount_value > 0),
    max_uses        INTEGER,                 -- null = ilimitado
    used_count      INTEGER NOT NULL DEFAULT 0,
    max_uses_per_user INTEGER DEFAULT 1,     -- 1 = un uso por persona
    min_ride_amount NUMERIC DEFAULT 0,       -- monto mínimo del viaje
    expires_at      TIMESTAMPTZ,             -- null = sin expiración
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    created_by      UUID REFERENCES public.profiles(id)
);
CREATE INDEX IF NOT EXISTS idx_promo_codes_code ON public.promo_codes(code) WHERE active = TRUE;

-- Tracking: qué código se aplicó a cada viaje (para impedir reuso por usuario).
CREATE TABLE IF NOT EXISTS public.ride_promos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ride_id         UUID NOT NULL REFERENCES public.rides(id) ON DELETE CASCADE,
    user_id         UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    promo_code      TEXT NOT NULL,
    discount_amount NUMERIC NOT NULL,
    applied_at      TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(ride_id)  -- un solo descuento por viaje
);
CREATE INDEX IF NOT EXISTS idx_ride_promos_user_code ON public.ride_promos(user_id, promo_code);

ALTER TABLE public.promo_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ride_promos ENABLE ROW LEVEL SECURITY;

-- Cualquier usuario autenticado puede leer códigos activos (los necesita para validar).
DROP POLICY IF EXISTS "anyone_read_active_promos" ON public.promo_codes;
CREATE POLICY "anyone_read_active_promos"
    ON public.promo_codes FOR SELECT
    TO authenticated
    USING (active = TRUE);

-- Sólo admins pueden crear/editar promos.
DROP POLICY IF EXISTS "admins_manage_promos" ON public.promo_codes;
CREATE POLICY "admins_manage_promos"
    ON public.promo_codes FOR ALL
    TO authenticated
    USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'))
    WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- Usuarios ven sólo sus aplicaciones de códigos.
DROP POLICY IF EXISTS "users_read_own_ride_promos" ON public.ride_promos;
CREATE POLICY "users_read_own_ride_promos"
    ON public.ride_promos FOR SELECT
    TO authenticated
    USING (user_id = auth.uid());

-- ------------------------------------------------------------
-- RPC: validar y aplicar un código promocional a un viaje
-- ------------------------------------------------------------
-- Devuelve { valid, discount_amount, final_price, message }
CREATE OR REPLACE FUNCTION public.apply_promo_code(
    p_code TEXT,
    p_ride_id UUID,
    p_user_id UUID,
    p_ride_amount NUMERIC
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_promo public.promo_codes%ROWTYPE;
    v_uses_by_user INTEGER;
    v_discount NUMERIC;
    v_final NUMERIC;
BEGIN
    -- Buscar el código activo
    SELECT * INTO v_promo
      FROM public.promo_codes
     WHERE code = UPPER(p_code) AND active = TRUE;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('valid', FALSE, 'message', 'Código inválido o inactivo');
    END IF;

    -- Vencimiento
    IF v_promo.expires_at IS NOT NULL AND v_promo.expires_at < NOW() THEN
        RETURN jsonb_build_object('valid', FALSE, 'message', 'El código ha expirado');
    END IF;

    -- Cupo máximo global
    IF v_promo.max_uses IS NOT NULL AND v_promo.used_count >= v_promo.max_uses THEN
        RETURN jsonb_build_object('valid', FALSE, 'message', 'El código alcanzó su límite de usos');
    END IF;

    -- Cupo por usuario
    SELECT COUNT(*) INTO v_uses_by_user
      FROM public.ride_promos
     WHERE user_id = p_user_id AND promo_code = v_promo.code;
    IF v_uses_by_user >= COALESCE(v_promo.max_uses_per_user, 1) THEN
        RETURN jsonb_build_object('valid', FALSE, 'message', 'Ya usaste este código antes');
    END IF;

    -- Monto mínimo
    IF p_ride_amount < COALESCE(v_promo.min_ride_amount, 0) THEN
        RETURN jsonb_build_object('valid', FALSE,
            'message', format('El viaje debe ser de al menos $%s', v_promo.min_ride_amount));
    END IF;

    -- Calcular descuento
    IF v_promo.discount_type = 'percent' THEN
        v_discount := ROUND(p_ride_amount * v_promo.discount_value / 100.0, 2);
    ELSE
        v_discount := LEAST(v_promo.discount_value, p_ride_amount);
    END IF;
    v_final := GREATEST(p_ride_amount - v_discount, 0);

    -- Insertar uso (UNIQUE en ride_id evita doble aplicación)
    INSERT INTO public.ride_promos (ride_id, user_id, promo_code, discount_amount)
    VALUES (p_ride_id, p_user_id, v_promo.code, v_discount);

    -- Incrementar contador global
    UPDATE public.promo_codes SET used_count = used_count + 1 WHERE id = v_promo.id;

    RETURN jsonb_build_object(
        'valid', TRUE,
        'discount_amount', v_discount,
        'final_price', v_final,
        'message', format('Descuento aplicado: $%s', v_discount)
    );
END;
$$;

GRANT EXECUTE ON FUNCTION public.apply_promo_code(TEXT, UUID, UUID, NUMERIC) TO authenticated;

-- ------------------------------------------------------------
-- B) REFERIDOS — código único por usuario, crédito al primer viaje
-- ------------------------------------------------------------

-- Cada profile gana un código de referido auto-generado al primer SELECT.
ALTER TABLE public.profiles
    ADD COLUMN IF NOT EXISTS referral_code TEXT UNIQUE,
    ADD COLUMN IF NOT EXISTS referral_credit_balance NUMERIC DEFAULT 0;

-- Generador de códigos cortos legibles (sin caracteres ambiguos).
CREATE OR REPLACE FUNCTION public.gen_referral_code()
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
    chars TEXT := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';  -- sin O, 0, I, 1
    code  TEXT := '';
    i INT;
BEGIN
    FOR i IN 1..6 LOOP
        code := code || substr(chars, 1 + (random() * (length(chars) - 1))::int, 1);
    END LOOP;
    RETURN code;
END;
$$;

-- Trigger: asigna referral_code al insertar profile.
CREATE OR REPLACE FUNCTION public.assign_referral_code()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_code TEXT;
    v_attempts INT := 0;
BEGIN
    IF NEW.referral_code IS NOT NULL THEN
        RETURN NEW;
    END IF;
    LOOP
        v_code := public.gen_referral_code();
        EXIT WHEN NOT EXISTS (SELECT 1 FROM public.profiles WHERE referral_code = v_code);
        v_attempts := v_attempts + 1;
        EXIT WHEN v_attempts > 10;
    END LOOP;
    NEW.referral_code := v_code;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_assign_referral_code ON public.profiles;
CREATE TRIGGER trg_assign_referral_code
    BEFORE INSERT ON public.profiles
    FOR EACH ROW
    EXECUTE FUNCTION public.assign_referral_code();

-- Backfill de códigos para profiles existentes (one-shot).
UPDATE public.profiles
   SET referral_code = public.gen_referral_code()
 WHERE referral_code IS NULL;

-- Tabla de referidos: vinculación entre quien refirió y quien fue referido.
CREATE TABLE IF NOT EXISTS public.referrals (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referrer_id   UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    referred_id   UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    referral_code TEXT NOT NULL,
    status        TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','credited','cancelled')),
    credit_amount NUMERIC NOT NULL DEFAULT 1.00,  -- $1 por defecto a cada parte
    credited_at   TIMESTAMPTZ,
    created_at    TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(referred_id)  -- un usuario sólo puede ser referido una vez
);
CREATE INDEX IF NOT EXISTS idx_referrals_referrer ON public.referrals(referrer_id);

ALTER TABLE public.referrals ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "users_read_own_referrals" ON public.referrals;
CREATE POLICY "users_read_own_referrals"
    ON public.referrals FOR SELECT
    TO authenticated
    USING (referrer_id = auth.uid() OR referred_id = auth.uid());

-- ------------------------------------------------------------
-- RPC: registrar un referido al momento del signup
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.register_referral(p_code TEXT, p_referred_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_referrer_id UUID;
BEGIN
    SELECT id INTO v_referrer_id FROM public.profiles WHERE referral_code = UPPER(p_code);
    IF v_referrer_id IS NULL THEN
        RETURN jsonb_build_object('ok', FALSE, 'message', 'Código de referido inválido');
    END IF;
    IF v_referrer_id = p_referred_id THEN
        RETURN jsonb_build_object('ok', FALSE, 'message', 'No puedes referirte a ti mismo');
    END IF;

    INSERT INTO public.referrals (referrer_id, referred_id, referral_code)
    VALUES (v_referrer_id, p_referred_id, UPPER(p_code))
    ON CONFLICT (referred_id) DO NOTHING;

    RETURN jsonb_build_object('ok', TRUE, 'referrer_id', v_referrer_id);
END;
$$;

GRANT EXECUTE ON FUNCTION public.register_referral(TEXT, UUID) TO authenticated;

-- ------------------------------------------------------------
-- RPC: acreditar referidos pendientes cuando se completa el primer viaje
-- ------------------------------------------------------------
-- Llamar desde el cliente (o desde un trigger) cuando un ride pasa a 'completed'.
CREATE OR REPLACE FUNCTION public.credit_pending_referral(p_user_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_ref public.referrals%ROWTYPE;
BEGIN
    SELECT * INTO v_ref FROM public.referrals
     WHERE referred_id = p_user_id AND status = 'pending'
     LIMIT 1;
    IF NOT FOUND THEN
        RETURN jsonb_build_object('ok', FALSE, 'message', 'Sin referido pendiente');
    END IF;

    -- Crédito a ambos
    UPDATE public.profiles
       SET referral_credit_balance = COALESCE(referral_credit_balance, 0) + v_ref.credit_amount
     WHERE id IN (v_ref.referrer_id, v_ref.referred_id);

    UPDATE public.referrals
       SET status = 'credited', credited_at = NOW()
     WHERE id = v_ref.id;

    RETURN jsonb_build_object('ok', TRUE, 'credit_amount', v_ref.credit_amount);
END;
$$;

GRANT EXECUTE ON FUNCTION public.credit_pending_referral(UUID) TO authenticated;
