-- ============================================================
-- 16 · Poller de Banesco (PULL cada 2 min via cron) + BCV + RPC
-- ============================================================
-- Lee la spec completa en docs/plan-banesco.md
--
-- Este script es idempotente: se puede correr varias veces sin
-- romper datos existentes. Todas las tablas se crean con
-- IF NOT EXISTS y los GRANTs/constraints usan DO blocks defensivos.
-- ============================================================

-- ------------------------------------------------------------
-- A) IDEMPOTENCIA DE MEMBRESÍAS POR REFERENCIA
-- ------------------------------------------------------------
-- Una transacción de Banesco es única por (payment_method, reference).
-- Si el poller re-procesa una tx (por overlap del cursor), la
-- inserción en driver_memberships viola esta UNIQUE y el RPC
-- retorna "duplicate".
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_memberships_method_reference'
    ) THEN
        ALTER TABLE public.driver_memberships
            ADD CONSTRAINT uq_memberships_method_reference
            UNIQUE (payment_method, reference);
    END IF;
END $$;

-- ------------------------------------------------------------
-- B) PAGOS SIN IDENTIFICAR (cola para revisión manual)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.banesco_unmatched_payments (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone                   TEXT,
    amount_bs               NUMERIC,
    amount_bs_expected      NUMERIC,
    reference               TEXT,
    paid_at                 TIMESTAMPTZ,
    channel                 TEXT,
    raw_payload             JSONB,
    status                  TEXT NOT NULL DEFAULT 'pending'
                                CHECK (status IN ('pending','amount_mismatch','normalize_error','resolved')),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_by             UUID REFERENCES public.profiles(id),
    resolved_at             TIMESTAMPTZ,
    resolved_membership_id  BIGINT REFERENCES public.driver_memberships(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_unmatched_status_created
    ON public.banesco_unmatched_payments(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_unmatched_reference
    ON public.banesco_unmatched_payments(reference);

ALTER TABLE public.banesco_unmatched_payments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admins_manage_unmatched" ON public.banesco_unmatched_payments;
CREATE POLICY "admins_manage_unmatched"
    ON public.banesco_unmatched_payments FOR ALL
    TO authenticated
    USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'))
    WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- ------------------------------------------------------------
-- C) CACHE DE TASA BCV (fila única, id=1)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.bcv_rate_cache (
    id          INT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    rate        NUMERIC NOT NULL CHECK (rate > 0),
    fetched_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.bcv_rate_cache ENABLE ROW LEVEL SECURITY;

-- Cualquier logueado puede LEER la tasa (la usa la UI del driver
-- para mostrar cuánto pagar en bolívares).
DROP POLICY IF EXISTS "anyone_read_bcv" ON public.bcv_rate_cache;
CREATE POLICY "anyone_read_bcv"
    ON public.bcv_rate_cache FOR SELECT
    TO anon, authenticated
    USING (TRUE);

-- Solo el poller (service_role) escribe.

-- ------------------------------------------------------------
-- D) CURSOR DEL POLLER (fila única, id=1)
-- ------------------------------------------------------------
-- last_cursor = timestamp "hasta dónde procesamos tx".
-- La próxima corrida consulta Banesco desde (last_cursor - overlap).
-- Si el poller nunca corrió, arranca desde NOW() y va hacia adelante.
CREATE TABLE IF NOT EXISTS public.banesco_poll_state (
    id                INT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    last_cursor       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_run_at       TIMESTAMPTZ,
    last_run_result   JSONB
);

INSERT INTO public.banesco_poll_state (id, last_cursor)
VALUES (1, NOW())
ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.banesco_poll_state ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admins_read_poll_state" ON public.banesco_poll_state;
CREATE POLICY "admins_read_poll_state"
    ON public.banesco_poll_state FOR SELECT
    TO authenticated
    USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- ------------------------------------------------------------
-- E) NORMALIZACIÓN DE TELÉFONO
-- ------------------------------------------------------------
-- "0058-414 123-4567"  → "04141234567"
-- "+58 414 123 4567"   → "04141234567"
-- "584141234567"       → "04141234567"
-- "4141234567"         → "04141234567"
CREATE OR REPLACE FUNCTION public.normalize_ve_phone(p_raw TEXT)
RETURNS TEXT
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
    digits TEXT;
BEGIN
    IF p_raw IS NULL THEN RETURN NULL; END IF;
    digits := regexp_replace(p_raw, '\D', '', 'g');
    IF digits IS NULL OR length(digits) = 0 THEN RETURN NULL; END IF;

    -- Quitar prefijo país 58 (con o sin 00 antes)
    IF digits LIKE '0058%' THEN digits := substring(digits FROM 5); END IF;
    IF digits LIKE '58%' AND length(digits) >= 12 THEN digits := substring(digits FROM 3); END IF;

    -- Asegurar prefijo 0 del operador venezolano
    IF length(digits) = 10 AND substring(digits FROM 1 FOR 1) IN ('4') THEN
        digits := '0' || digits;
    END IF;

    RETURN digits;
END;
$$;

-- ------------------------------------------------------------
-- F) USD POR PLAN (derivado de vehicle_type)
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.membership_usd_for_vehicle(p_vehicle_type TEXT)
RETURNS NUMERIC
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
    v TEXT := lower(coalesce(p_vehicle_type, 'standard'));
BEGIN
    IF v = 'moto' THEN RETURN 10;
    ELSIF v IN ('van', 'camioneta') THEN RETURN 25;
    ELSE RETURN 20; -- carro / standard
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.membership_plan_for_vehicle(p_vehicle_type TEXT)
RETURNS TEXT
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
    v TEXT := lower(coalesce(p_vehicle_type, 'standard'));
BEGIN
    IF v = 'moto' THEN RETURN 'moto';
    ELSIF v IN ('van', 'camioneta') THEN RETURN 'van';
    ELSE RETURN 'standard';
    END IF;
END;
$$;

-- ------------------------------------------------------------
-- G) RPC PRINCIPAL: register_membership_from_payment
-- ------------------------------------------------------------
-- Invocada por el poller PHP con service_role. Busca el driver
-- por teléfono, valida monto contra (USD × BCV) con tolerancia,
-- y crea la membresía (el trigger existente activa el profile).
--
-- Retorna JSONB con uno de estos shapes:
--   {status:'created', membership_id, driver_id}
--   {status:'duplicate'}                                  -- reference ya existe
--   {status:'unmatched'}                                  -- phone no matchea ningún driver
--   {status:'amount_mismatch', expected_bs, received_bs}  -- fuera de tolerancia
CREATE OR REPLACE FUNCTION public.register_membership_from_payment(
    p_phone          TEXT,
    p_amount_bs      NUMERIC,
    p_reference      TEXT,
    p_paid_at        TIMESTAMPTZ,
    p_channel        TEXT,
    p_bcv_rate       NUMERIC,
    p_tolerance_pct  NUMERIC DEFAULT 1.0,
    p_raw_payload    JSONB DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_phone_norm   TEXT;
    v_driver       RECORD;
    v_plan_usd     NUMERIC;
    v_plan_code    TEXT;
    v_expected_bs  NUMERIC;
    v_diff_pct     NUMERIC;
    v_expires_at   TIMESTAMPTZ;
    v_membership_id BIGINT;
BEGIN
    -- Validaciones básicas
    IF p_bcv_rate IS NULL OR p_bcv_rate <= 0 THEN
        RAISE EXCEPTION 'invalid_bcv_rate';
    END IF;
    IF p_reference IS NULL OR length(p_reference) = 0 THEN
        RAISE EXCEPTION 'missing_reference';
    END IF;

    v_phone_norm := public.normalize_ve_phone(p_phone);

    -- Buscar driver por teléfono normalizado
    SELECT id, vehicle_type INTO v_driver
      FROM public.profiles
     WHERE role = 'driver'
       AND public.normalize_ve_phone(phone) = v_phone_norm
     LIMIT 1;

    IF NOT FOUND THEN
        INSERT INTO public.banesco_unmatched_payments
            (phone, amount_bs, reference, paid_at, channel, raw_payload, status)
        VALUES
            (p_phone, p_amount_bs, p_reference, p_paid_at, p_channel, p_raw_payload, 'pending')
        ON CONFLICT DO NOTHING;
        RETURN jsonb_build_object('status', 'unmatched');
    END IF;

    -- Calcular monto esperado en Bs y validar tolerancia
    v_plan_usd    := public.membership_usd_for_vehicle(v_driver.vehicle_type);
    v_plan_code   := public.membership_plan_for_vehicle(v_driver.vehicle_type);
    v_expected_bs := round((v_plan_usd * p_bcv_rate)::numeric, 2);
    v_diff_pct    := abs(p_amount_bs - v_expected_bs) / v_expected_bs * 100.0;

    IF v_diff_pct > p_tolerance_pct THEN
        INSERT INTO public.banesco_unmatched_payments
            (phone, amount_bs, amount_bs_expected, reference, paid_at, channel, raw_payload, status)
        VALUES
            (p_phone, p_amount_bs, v_expected_bs, p_reference, p_paid_at, p_channel, p_raw_payload, 'amount_mismatch')
        ON CONFLICT DO NOTHING;
        RETURN jsonb_build_object(
            'status', 'amount_mismatch',
            'expected_bs', v_expected_bs,
            'received_bs', p_amount_bs,
            'diff_pct', round(v_diff_pct, 3)
        );
    END IF;

    -- Insertar membresía. Si la reference ya existe, capturamos el UNIQUE
    -- y devolvemos 'duplicate' sin crear duplicados.
    v_expires_at := p_paid_at + interval '30 days';

    BEGIN
        INSERT INTO public.driver_memberships
            (driver_id, plan, amount, period, payment_method, reference, paid_at, expires_at, status)
        VALUES
            (v_driver.id, v_plan_code, v_plan_usd, 'monthly', 'banesco', p_reference, p_paid_at, v_expires_at, 'active')
        RETURNING id INTO v_membership_id;
    EXCEPTION WHEN unique_violation THEN
        RETURN jsonb_build_object('status', 'duplicate');
    END;

    RETURN jsonb_build_object(
        'status', 'created',
        'membership_id', v_membership_id,
        'driver_id', v_driver.id
    );
END;
$$;

-- Solo el service_role puede ejecutar el RPC (es el que usa el poller PHP).
REVOKE ALL ON FUNCTION public.register_membership_from_payment(TEXT, NUMERIC, TEXT, TIMESTAMPTZ, TEXT, NUMERIC, NUMERIC, JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.register_membership_from_payment(TEXT, NUMERIC, TEXT, TIMESTAMPTZ, TEXT, NUMERIC, NUMERIC, JSONB) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.register_membership_from_payment(TEXT, NUMERIC, TEXT, TIMESTAMPTZ, TEXT, NUMERIC, NUMERIC, JSONB) TO service_role;

-- ------------------------------------------------------------
-- H) RPC AUXILIAR: get_expected_membership_amount
-- ------------------------------------------------------------
-- Usada por la página /driver/membresia para mostrarle al driver
-- cuántos Bs tiene que pagar. Devuelve USD del plan, tasa BCV
-- cacheada y producto.
CREATE OR REPLACE FUNCTION public.get_expected_membership_amount()
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_profile  RECORD;
    v_rate     NUMERIC;
    v_fetched  TIMESTAMPTZ;
    v_usd      NUMERIC;
    v_plan     TEXT;
BEGIN
    SELECT id, vehicle_type, phone
      INTO v_profile
      FROM public.profiles
     WHERE id = auth.uid()
     LIMIT 1;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('error', 'not_authenticated');
    END IF;

    SELECT rate, fetched_at INTO v_rate, v_fetched
      FROM public.bcv_rate_cache WHERE id = 1;

    v_usd  := public.membership_usd_for_vehicle(v_profile.vehicle_type);
    v_plan := public.membership_plan_for_vehicle(v_profile.vehicle_type);

    RETURN jsonb_build_object(
        'plan', v_plan,
        'vehicle_type', v_profile.vehicle_type,
        'phone', v_profile.phone,
        'amount_usd', v_usd,
        'bcv_rate', v_rate,
        'bcv_fetched_at', v_fetched,
        'amount_bs', CASE WHEN v_rate IS NOT NULL THEN round((v_usd * v_rate)::numeric, 2) ELSE NULL END
    );
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_expected_membership_amount() TO authenticated;
