-- ============================================================
-- 16 · Validación automática de pagos vía Banesco
-- ============================================================
--
-- Contexto:
--   El pasajero hace un pago móvil a la cuenta Banesco de Higo
--   (RIF J402638850, cuenta 01340332563321061868). Antes, ambas
--   partes tenían que confirmar manualmente con un botón
--   (payment_confirmed_by_user / payment_confirmed_by_driver).
--
--   Esta migración agrega un camino automático: el endpoint
--   public_html/banesco-validate.php consulta a Banesco con la
--   referencia + bank + phone que ingresó el pasajero, compara el
--   monto en Bs contra (price_usd × BCV) con tolerancia, y si match
--   llama a la RPC confirm_ride_payment_banesco con service_role.
--
--   Toda esta lógica corre del lado del servidor PHP. El cliente
--   nunca ve la respuesta cruda de Banesco — sólo "validado/no".
--
-- Nada de lo que hay acá rompe el flow manual: si Banesco se cae,
-- el botón "Confirmar pago" sigue funcionando como antes.
--
-- Idempotente: se puede correr varias veces. IF NOT EXISTS / OR REPLACE
-- en todo lo que aplica.

-- ------------------------------------------------------------
-- A) COLUMNAS NUEVAS EN rides
-- ------------------------------------------------------------
-- Distinguen una confirmación bilateral manual de una validación
-- automática por Banesco. Si payment_validated_at IS NOT NULL, la
-- confirmación vino del banco — no requiere que el conductor tilde nada.
ALTER TABLE public.rides
    ADD COLUMN IF NOT EXISTS payment_validated_at      TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS payment_validation_method TEXT,
    ADD COLUMN IF NOT EXISTS payment_validation_data   JSONB;

CREATE INDEX IF NOT EXISTS idx_rides_payment_reference
    ON public.rides(payment_reference)
    WHERE payment_reference IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_rides_payment_validated_at
    ON public.rides(payment_validated_at DESC)
    WHERE payment_validated_at IS NOT NULL;

-- ------------------------------------------------------------
-- B) TABLA DE AUDITORÍA: banesco_validation_attempts
-- ------------------------------------------------------------
-- Cada intento (exitoso o fallido) genera una fila. Sirve para:
--   - Disputas: si el pasajero dice "ya pagué" y la app no detectó
--     nada, podemos ver QUÉ envió y QUÉ respondió Banesco.
--   - Anti-abuso: rate-limiting per (user_id, ride_id) en el RPC.
--   - Telemetría operativa: cuánto rechazo, qué httpStatus comunes.
--
-- request_payload guarda lo que envió PHP a Banesco SIN credenciales.
-- response_body guarda la respuesta JSON cruda de Banesco (con el
-- match si lo hubo). Ningún token de Banesco vive acá.
CREATE TABLE IF NOT EXISTS public.banesco_validation_attempts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ride_id         UUID NOT NULL REFERENCES public.rides(id) ON DELETE CASCADE,
    user_id         UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    reference       TEXT NOT NULL,
    phone           TEXT,
    bank_id         TEXT,
    expected_bs     NUMERIC,
    bcv_rate        NUMERIC,
    matched_amount  NUMERIC,
    diff_pct        NUMERIC,
    banesco_status  TEXT,
    outcome         TEXT NOT NULL CHECK (outcome IN (
        'matched','amount_mismatch','no_credit','banesco_error','rejected'
    )),
    request_payload JSONB,
    response_body   JSONB,
    error_message   TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bva_ride
    ON public.banesco_validation_attempts(ride_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bva_user_recent
    ON public.banesco_validation_attempts(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bva_outcome
    ON public.banesco_validation_attempts(outcome, created_at DESC);

ALTER TABLE public.banesco_validation_attempts ENABLE ROW LEVEL SECURITY;

-- El usuario puede ver sus propios intentos (útil para mostrar "se
-- detectó tu pago" o "no encontramos nada con esa referencia").
DROP POLICY IF EXISTS "users_read_own_validation_attempts"
    ON public.banesco_validation_attempts;
CREATE POLICY "users_read_own_validation_attempts"
    ON public.banesco_validation_attempts FOR SELECT
    TO authenticated
    USING (user_id = auth.uid());

-- Admins ven todo.
DROP POLICY IF EXISTS "admins_read_all_validation_attempts"
    ON public.banesco_validation_attempts;
CREATE POLICY "admins_read_all_validation_attempts"
    ON public.banesco_validation_attempts FOR SELECT
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND role = 'admin'
        )
    );

-- Inserts/updates: SOLO service_role (vía PHP). Nada de cliente.
-- No hay policy para INSERT/UPDATE/DELETE → con RLS prendido los
-- otros roles quedan bloqueados de plano. service_role bypasea RLS.

-- ------------------------------------------------------------
-- C) RPC: confirm_ride_payment_banesco
-- ------------------------------------------------------------
-- Llamada por banesco-validate.php DESPUÉS de haber validado contra
-- Banesco que el pago existe. PHP ya verificó:
--   1. JWT del pasajero (firma + exp)
--   2. ride.user_id = jwt.sub
--   3. Banesco respondió 200 con un trnType='CR' cuyo amount está
--      dentro de la tolerancia de (price_usd × BCV)
--
-- La RPC sólo:
--   - Re-chequea autoría (defensa en profundidad).
--   - Marca user_confirmed=true y, si el driver ya confirmó, cierra
--     bilateralmente con payment_confirmed_at.
--   - Setea payment_validated_at + payment_validation_method/data.
--   - Loguea un attempt outcome='matched'.
--
-- IMPORTANTE: SECURITY DEFINER + revocada de PUBLIC. Sólo
-- service_role puede ejecutarla — nadie del cliente le pasa por arriba.
CREATE OR REPLACE FUNCTION public.confirm_ride_payment_banesco(
    p_ride_id        UUID,
    p_user_id        UUID,
    p_reference      TEXT,
    p_phone          TEXT,
    p_bank_id        TEXT,
    p_expected_bs    NUMERIC,
    p_bcv_rate       NUMERIC,
    p_matched_amount NUMERIC,
    p_diff_pct       NUMERIC,
    p_banesco_status TEXT,
    p_request        JSONB,
    p_response       JSONB
)
RETURNS public.rides
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_ride public.rides;
BEGIN
    SELECT * INTO v_ride FROM public.rides WHERE id = p_ride_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'ride_not_found' USING ERRCODE = 'P0002';
    END IF;
    IF v_ride.user_id <> p_user_id THEN
        RAISE EXCEPTION 'ride_owner_mismatch' USING ERRCODE = '42501';
    END IF;
    IF v_ride.status <> 'completed' THEN
        RAISE EXCEPTION 'ride_not_completed' USING ERRCODE = '22023';
    END IF;
    IF v_ride.payment_validated_at IS NOT NULL THEN
        -- Idempotencia: si ya fue validado, devolvemos el ride tal cual.
        RETURN v_ride;
    END IF;

    UPDATE public.rides
       SET payment_confirmed_by_user = TRUE,
           payment_method            = 'pago_movil',
           payment_reference         = p_reference,
           payment_validated_at      = NOW(),
           payment_validation_method = 'banesco_auto',
           payment_validation_data   = p_response,
           payment_confirmed_at      = CASE
               WHEN payment_confirmed_by_driver THEN NOW()
               ELSE payment_confirmed_at
           END
     WHERE id = p_ride_id
     RETURNING * INTO v_ride;

    INSERT INTO public.banesco_validation_attempts (
        ride_id, user_id, reference, phone, bank_id,
        expected_bs, bcv_rate, matched_amount, diff_pct,
        banesco_status, outcome, request_payload, response_body
    ) VALUES (
        p_ride_id, p_user_id, p_reference, p_phone, p_bank_id,
        p_expected_bs, p_bcv_rate, p_matched_amount, p_diff_pct,
        p_banesco_status, 'matched', p_request, p_response
    );

    RETURN v_ride;
END;
$$;

REVOKE ALL ON FUNCTION public.confirm_ride_payment_banesco(
    UUID, UUID, TEXT, TEXT, TEXT, NUMERIC, NUMERIC, NUMERIC, NUMERIC, TEXT, JSONB, JSONB
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.confirm_ride_payment_banesco(
    UUID, UUID, TEXT, TEXT, TEXT, NUMERIC, NUMERIC, NUMERIC, NUMERIC, TEXT, JSONB, JSONB
) TO service_role;

-- ------------------------------------------------------------
-- D) RPC: log_banesco_validation_failure
-- ------------------------------------------------------------
-- Para los casos en que Banesco no confirma (no_credit, mismatch,
-- error). Permite ver en el panel admin por qué falló y mostrarle
-- al usuario un mensaje útil. NO toca rides.
CREATE OR REPLACE FUNCTION public.log_banesco_validation_failure(
    p_ride_id        UUID,
    p_user_id        UUID,
    p_reference      TEXT,
    p_phone          TEXT,
    p_bank_id        TEXT,
    p_expected_bs    NUMERIC,
    p_bcv_rate       NUMERIC,
    p_banesco_status TEXT,
    p_outcome        TEXT,
    p_request        JSONB,
    p_response       JSONB,
    p_error_message  TEXT
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_id BIGINT;
BEGIN
    IF p_outcome NOT IN ('amount_mismatch','no_credit','banesco_error','rejected') THEN
        RAISE EXCEPTION 'invalid_outcome' USING ERRCODE = '22023';
    END IF;
    INSERT INTO public.banesco_validation_attempts (
        ride_id, user_id, reference, phone, bank_id,
        expected_bs, bcv_rate, banesco_status, outcome,
        request_payload, response_body, error_message
    ) VALUES (
        p_ride_id, p_user_id, p_reference, p_phone, p_bank_id,
        p_expected_bs, p_bcv_rate, p_banesco_status, p_outcome,
        p_request, p_response, p_error_message
    )
    RETURNING id INTO v_id;
    RETURN v_id;
END;
$$;

REVOKE ALL ON FUNCTION public.log_banesco_validation_failure(
    UUID, UUID, TEXT, TEXT, TEXT, NUMERIC, NUMERIC, TEXT, TEXT, JSONB, JSONB, TEXT
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.log_banesco_validation_failure(
    UUID, UUID, TEXT, TEXT, TEXT, NUMERIC, NUMERIC, TEXT, TEXT, JSONB, JSONB, TEXT
) TO service_role;

-- ------------------------------------------------------------
-- E) RPC pública: count_recent_validation_attempts
-- ------------------------------------------------------------
-- El cliente la llama antes de enviar a banesco-validate.php para
-- mostrar "ya intentaste 3 veces, esperá un poco". El PHP TAMBIÉN
-- la usa como rate-limit duro server-side: > 5 intentos en 10 min
-- para el mismo (user, ride) → 429.
CREATE OR REPLACE FUNCTION public.count_recent_validation_attempts(
    p_ride_id   UUID,
    p_user_id   UUID,
    p_window_min INT DEFAULT 10
)
RETURNS INT
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT COUNT(*)::INT
    FROM public.banesco_validation_attempts
    WHERE ride_id = p_ride_id
      AND user_id = p_user_id
      AND created_at > NOW() - (p_window_min || ' minutes')::INTERVAL;
$$;

GRANT EXECUTE ON FUNCTION public.count_recent_validation_attempts(UUID, UUID, INT)
    TO authenticated, service_role;
