-- ============================================================
-- 16 · Higo Pay — auto-contenida (incluye dependencias de mig 13)
-- ============================================================
-- Soporta el portal /higo-pay donde el conductor reporta un pago
-- de membresía y la app lo valida contra Banesco. Cada consulta
-- queda auditada en payment_reports; las exitosas además crean
-- una fila en driver_memberships.
--
-- Si las tablas/columnas/triggers de la migración 13 no existen,
-- esta migración los crea acá (idempotente). Si ya existen, no
-- los toca. Se puede correr cuantas veces haga falta sin romper.
-- ============================================================

-- ════════════════════════════════════════════════════════════
-- DEPENDENCIAS DE LA MIGRACIÓN 13 (idempotentes)
-- ════════════════════════════════════════════════════════════

-- Columnas en profiles para estado de membresía.
ALTER TABLE public.profiles
    ADD COLUMN IF NOT EXISTS subscription_status TEXT DEFAULT 'suspended',
    ADD COLUMN IF NOT EXISTS last_payment_date   TIMESTAMPTZ;

-- Columnas en rides para confirmación bilateral de pago.
ALTER TABLE public.rides
    ADD COLUMN IF NOT EXISTS payment_method              TEXT DEFAULT 'pago_movil',
    ADD COLUMN IF NOT EXISTS payment_reference           TEXT,
    ADD COLUMN IF NOT EXISTS payment_confirmed_by_user   BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS payment_confirmed_by_driver BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS payment_confirmed_at        TIMESTAMPTZ;

-- Tabla driver_memberships.
CREATE TABLE IF NOT EXISTS public.driver_memberships (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id      UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    plan           TEXT NOT NULL CHECK (plan IN ('moto','standard','van')),
    amount         NUMERIC NOT NULL,
    period         TEXT NOT NULL DEFAULT 'monthly' CHECK (period IN ('weekly','monthly','yearly')),
    payment_method TEXT NOT NULL DEFAULT 'pago_movil',
    reference      TEXT,
    paid_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at     TIMESTAMPTZ NOT NULL,
    status         TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','expired','refunded')),
    notes          TEXT,
    created_at     TIMESTAMPTZ DEFAULT NOW(),
    created_by     UUID REFERENCES public.profiles(id)
);

CREATE INDEX IF NOT EXISTS idx_memberships_driver
    ON public.driver_memberships(driver_id, expires_at DESC);
CREATE INDEX IF NOT EXISTS idx_memberships_active_expires
    ON public.driver_memberships(expires_at)
    WHERE status = 'active';

ALTER TABLE public.driver_memberships ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "drivers_read_own_memberships" ON public.driver_memberships;
CREATE POLICY "drivers_read_own_memberships"
    ON public.driver_memberships FOR SELECT
    TO authenticated
    USING (driver_id = auth.uid());

DROP POLICY IF EXISTS "admins_manage_memberships" ON public.driver_memberships;
CREATE POLICY "admins_manage_memberships"
    ON public.driver_memberships FOR ALL
    TO authenticated
    USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'))
    WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- Helper: ¿el conductor tiene membresía activa?
CREATE OR REPLACE FUNCTION public.driver_has_active_membership(p_driver_id UUID)
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.driver_memberships
        WHERE driver_id = p_driver_id
          AND status = 'active'
          AND expires_at > NOW()
    );
$$;

GRANT EXECUTE ON FUNCTION public.driver_has_active_membership(UUID) TO authenticated;

-- Trigger: sync profiles.subscription_status ← driver_memberships.
CREATE OR REPLACE FUNCTION public.sync_driver_subscription_status()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    UPDATE public.profiles
       SET subscription_status = CASE
               WHEN public.driver_has_active_membership(NEW.driver_id) THEN 'active'
               ELSE 'suspended'
           END,
           last_payment_date = NEW.paid_at
     WHERE id = NEW.driver_id;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_subscription_status ON public.driver_memberships;
CREATE TRIGGER trg_sync_subscription_status
    AFTER INSERT OR UPDATE ON public.driver_memberships
    FOR EACH ROW
    EXECUTE FUNCTION public.sync_driver_subscription_status();

-- ════════════════════════════════════════════════════════════
-- HIGO PAY (lo nuevo de la migración 16)
-- ════════════════════════════════════════════════════════════

-- ------------------------------------------------------------
-- A) Catálogo de planes de membresía (precio + duración)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.membership_plans (
    plan          TEXT PRIMARY KEY CHECK (plan IN ('moto','standard','van')),
    period        TEXT NOT NULL CHECK (period IN ('weekly','monthly','yearly')),
    amount_usd    NUMERIC NOT NULL CHECK (amount_usd > 0),
    amount_bs     NUMERIC,
    bs_updated_at TIMESTAMPTZ,
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by    UUID REFERENCES public.profiles(id)
);

INSERT INTO public.membership_plans (plan, period, amount_usd, amount_bs, bs_updated_at, active) VALUES
    ('moto',     'monthly',  5.00, NULL, NULL, TRUE),
    ('standard', 'monthly', 10.00, NULL, NULL, TRUE),
    ('van',      'monthly', 15.00, NULL, NULL, TRUE)
ON CONFLICT (plan) DO NOTHING;

ALTER TABLE public.membership_plans ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anyone_read_membership_plans" ON public.membership_plans;
CREATE POLICY "anyone_read_membership_plans"
    ON public.membership_plans FOR SELECT
    TO anon, authenticated
    USING (TRUE);

DROP POLICY IF EXISTS "admins_manage_membership_plans" ON public.membership_plans;
CREATE POLICY "admins_manage_membership_plans"
    ON public.membership_plans FOR ALL
    TO authenticated
    USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'))
    WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

CREATE OR REPLACE FUNCTION public.touch_membership_plans()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := NOW();
    NEW.updated_by := auth.uid();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_membership_plans ON public.membership_plans;
CREATE TRIGGER trg_touch_membership_plans
    BEFORE UPDATE ON public.membership_plans
    FOR EACH ROW EXECUTE FUNCTION public.touch_membership_plans();

-- ------------------------------------------------------------
-- B) Auditoría de cada consulta a Banesco
-- ------------------------------------------------------------
-- Toda llamada a /api/banesco-validate.php se registra acá, haya
-- sido validada o no. Permite reconciliación, soporte y antifraude.
CREATE TABLE IF NOT EXISTS public.payment_reports (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id       UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    bank_origin     TEXT NOT NULL,
    reference_last6 TEXT NOT NULL,
    sender_phone    TEXT,
    amount_reported NUMERIC NOT NULL,
    amount_real     NUMERIC,
    trn_date        DATE NOT NULL,
    banesco_status  TEXT,
    status          TEXT NOT NULL CHECK (status IN ('validated','rejected','pending')),
    membership_id   BIGINT REFERENCES public.driver_memberships(id) ON DELETE SET NULL,
    error_message   TEXT,
    raw_response    JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_payment_reports_driver
    ON public.payment_reports(driver_id, created_at DESC);

-- Previene reusar la misma referencia dos veces como pago válido.
CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_reports_ref_validated
    ON public.payment_reports(bank_origin, reference_last6, trn_date)
    WHERE status = 'validated';

ALTER TABLE public.payment_reports ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "drivers_read_own_reports" ON public.payment_reports;
CREATE POLICY "drivers_read_own_reports"
    ON public.payment_reports FOR SELECT
    TO authenticated
    USING (driver_id = auth.uid());

DROP POLICY IF EXISTS "drivers_insert_own_reports" ON public.payment_reports;
CREATE POLICY "drivers_insert_own_reports"
    ON public.payment_reports FOR INSERT
    TO authenticated
    WITH CHECK (driver_id = auth.uid());

DROP POLICY IF EXISTS "admins_manage_reports" ON public.payment_reports;
CREATE POLICY "admins_manage_reports"
    ON public.payment_reports FOR ALL
    TO authenticated
    USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'))
    WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- ------------------------------------------------------------
-- C) RPC atómico: registra payment_report validado + crea membresía
-- ------------------------------------------------------------
-- SECURITY DEFINER porque cruza dos tablas y necesita aplicar la
-- regla de unicidad sobre payment_reports incluso cuando el driver
-- intenta reusar la misma referencia.
CREATE OR REPLACE FUNCTION public.register_membership_payment(
    p_bank_origin     TEXT,
    p_reference_last6 TEXT,
    p_sender_phone    TEXT,
    p_amount_reported NUMERIC,
    p_amount_real     NUMERIC,
    p_trn_date        DATE,
    p_banesco_status  TEXT,
    p_raw_response    JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_driver        UUID := auth.uid();
    v_plan          TEXT;
    v_period        TEXT;
    v_membership_id BIGINT;
    v_report_id     BIGINT;
    v_expires       TIMESTAMPTZ;
BEGIN
    IF v_driver IS NULL THEN
        RAISE EXCEPTION 'no auth' USING ERRCODE = '28000';
    END IF;

    -- Plan tomado de profiles.vehicle_model; default 'standard'.
    SELECT COALESCE(NULLIF(vehicle_model,''), 'standard')
      INTO v_plan
      FROM public.profiles
     WHERE id = v_driver;

    SELECT period INTO v_period
      FROM public.membership_plans
     WHERE plan = v_plan;
    IF v_period IS NULL THEN v_period := 'monthly'; END IF;

    v_expires := CASE v_period
        WHEN 'weekly'  THEN NOW() + INTERVAL '7 days'
        WHEN 'monthly' THEN NOW() + INTERVAL '30 days'
        WHEN 'yearly'  THEN NOW() + INTERVAL '365 days'
    END;

    INSERT INTO public.driver_memberships
        (driver_id, plan, amount, period, payment_method, reference, paid_at, expires_at, status)
    VALUES
        (v_driver, v_plan, p_amount_real, v_period, 'banesco',
         p_reference_last6, NOW(), v_expires, 'active')
    RETURNING id INTO v_membership_id;

    INSERT INTO public.payment_reports
        (driver_id, bank_origin, reference_last6, sender_phone,
         amount_reported, amount_real, trn_date,
         banesco_status, status, membership_id, raw_response)
    VALUES
        (v_driver, p_bank_origin, p_reference_last6, p_sender_phone,
         p_amount_reported, p_amount_real, p_trn_date,
         p_banesco_status, 'validated', v_membership_id, p_raw_response)
    RETURNING id INTO v_report_id;

    RETURN jsonb_build_object(
        'membership_id', v_membership_id,
        'report_id',     v_report_id,
        'expires_at',    v_expires
    );
END;
$$;

GRANT EXECUTE ON FUNCTION public.register_membership_payment(
    TEXT, TEXT, TEXT, NUMERIC, NUMERIC, DATE, TEXT, JSONB
) TO authenticated;
