-- ============================================================
-- 18 · Notificaciones push de vencimiento de membresía
-- ============================================================
-- Soporta el cron PHP `/api/send-membership-reminders.php` que
-- avisa al conductor antes de que se le venza la membresía. Las
-- piezas son:
--   A) profiles.fcm_token      → token FCM web/Android del driver
--   B) profiles.fcm_updated_at → para limpiar tokens viejos
--   C) membership_reminders     → bitácora anti-doble-envío

-- ------------------------------------------------------------
-- A · Token FCM en profiles
-- ------------------------------------------------------------
-- El cliente lo escribe cada vez que Firebase lo entrega/refresca.
-- RLS existente (el usuario sólo edita su fila) ya cubre la escritura.
ALTER TABLE public.profiles
    ADD COLUMN IF NOT EXISTS fcm_token      TEXT,
    ADD COLUMN IF NOT EXISTS fcm_updated_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_profiles_fcm_token
    ON public.profiles(fcm_token)
    WHERE fcm_token IS NOT NULL;

-- ------------------------------------------------------------
-- B · Bitácora de recordatorios enviados
-- ------------------------------------------------------------
-- Una fila por (membresía, umbral en días). El índice único impide
-- que el cron mande dos veces el mismo aviso si corre con frecuencia.
CREATE TABLE IF NOT EXISTS public.membership_reminders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id       UUID    NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    membership_id   BIGINT  NOT NULL REFERENCES public.driver_memberships(id) ON DELETE CASCADE,
    days_threshold  INTEGER NOT NULL CHECK (days_threshold IN (7, 3, 1, 0)),
    sent_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fcm_status      TEXT,
    error_message   TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_membership_reminders_membership_threshold
    ON public.membership_reminders(membership_id, days_threshold);

CREATE INDEX IF NOT EXISTS idx_membership_reminders_driver
    ON public.membership_reminders(driver_id, sent_at DESC);

ALTER TABLE public.membership_reminders ENABLE ROW LEVEL SECURITY;

-- El driver puede ver sus propios recordatorios (debug/UX futura).
-- La escritura la hace exclusivamente service_role desde el cron PHP.
DROP POLICY IF EXISTS "drivers_read_own_reminders" ON public.membership_reminders;
CREATE POLICY "drivers_read_own_reminders"
    ON public.membership_reminders FOR SELECT
    TO authenticated
    USING (driver_id = auth.uid());

DROP POLICY IF EXISTS "admins_manage_reminders" ON public.membership_reminders;
CREATE POLICY "admins_manage_reminders"
    ON public.membership_reminders FOR ALL
    TO authenticated
    USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'))
    WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));
