-- ============================================================
-- 20 · Zonas de cobertura geográfica
-- ============================================================
-- Cada zona es un círculo definido por (center_lat, center_lng, radius_km).
-- La RPC is_within_coverage usa Haversine (igual que get_nearby_rides) sin PostGIS.

CREATE TABLE IF NOT EXISTS public.coverage_zones (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL,
    center_lat FLOAT8 NOT NULL,
    center_lng FLOAT8 NOT NULL,
    radius_km  FLOAT8 NOT NULL DEFAULT 30.0,
    active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.coverage_zones ENABLE ROW LEVEL SECURITY;

-- Cualquier usuario autenticado puede leer zonas activas
DROP POLICY IF EXISTS "anyone_read_active_zones" ON public.coverage_zones;
CREATE POLICY "anyone_read_active_zones"
    ON public.coverage_zones FOR SELECT TO authenticated
    USING (active = TRUE);

-- Solo admins gestionan zonas
DROP POLICY IF EXISTS "admins_manage_zones" ON public.coverage_zones;
CREATE POLICY "admins_manage_zones"
    ON public.coverage_zones FOR ALL TO authenticated
    USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'))
    WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- ¿Está (lat, lng) dentro de alguna zona activa?
CREATE OR REPLACE FUNCTION public.is_within_coverage(p_lat float8, p_lng float8)
RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1 FROM public.coverage_zones
        WHERE active = TRUE
          AND 2 * 6371 * asin(sqrt(
              power(sin(radians((center_lat - p_lat) / 2)), 2)
              + cos(radians(p_lat)) * cos(radians(center_lat))
              * power(sin(radians((center_lng - p_lng) / 2)), 2)
          )) <= radius_km
    );
$$;

GRANT EXECUTE ON FUNCTION public.is_within_coverage(float8, float8) TO authenticated;

-- Zona inicial: Higuerote y área metropolitana
INSERT INTO public.coverage_zones (name, center_lat, center_lng, radius_km)
VALUES ('Higuerote', 10.4653, -65.9711, 35.0)
ON CONFLICT DO NOTHING;
