-- ============================================================
-- 24 · ride_messages — tabla del chat in-ride + RLS + realtime
-- ============================================================
-- La migración 03 original creaba public.messages, pero el frontend usa
-- public.ride_messages. En producción la tabla existe (driver→passenger
-- inserta sin error) pero el pasajero no recibía los mensajes:
--   - Sin SELECT policy explícita para passenger/driver del mismo ride.
--   - Tabla no incluida en la publication supabase_realtime, así que el
--     canal postgres_changes nunca disparaba INSERT.
-- Esta migración deja todo idempotente.

CREATE TABLE IF NOT EXISTS public.ride_messages (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    ride_id     BIGINT NOT NULL REFERENCES public.rides(id) ON DELETE CASCADE,
    sender_id   UUID   NOT NULL REFERENCES auth.users(id),
    content     TEXT   NOT NULL,
    is_read     BOOLEAN DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_ride_messages_ride_id
    ON public.ride_messages (ride_id, created_at);

ALTER TABLE public.ride_messages ENABLE ROW LEVEL SECURITY;

-- SELECT: passenger y driver del ride
DROP POLICY IF EXISTS "ride_messages_select_participants" ON public.ride_messages;
CREATE POLICY "ride_messages_select_participants"
    ON public.ride_messages FOR SELECT TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.rides r
            WHERE r.id = ride_messages.ride_id
              AND (r.user_id = auth.uid() OR r.driver_id = auth.uid())
        )
    );

-- INSERT: solo participantes, y solo como uno mismo
DROP POLICY IF EXISTS "ride_messages_insert_participants" ON public.ride_messages;
CREATE POLICY "ride_messages_insert_participants"
    ON public.ride_messages FOR INSERT TO authenticated
    WITH CHECK (
        sender_id = auth.uid()
        AND EXISTS (
            SELECT 1 FROM public.rides r
            WHERE r.id = ride_messages.ride_id
              AND (r.user_id = auth.uid() OR r.driver_id = auth.uid())
        )
    );

-- Realtime: añadir a la publication si aún no está.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
          AND schemaname = 'public'
          AND tablename = 'ride_messages'
    ) THEN
        EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.ride_messages';
    END IF;
END $$;
