-- ============================================================
-- 25 · support_threads + support_messages — chat usuario ↔ equipo Higo
-- ============================================================
-- Canal de soporte 1-a-1 entre cada usuario (pasajero o conductor) y los
-- admins del equipo Higo. Un único hilo por usuario (estilo WhatsApp).
-- Separado de ride_messages (chat in-ride) y de AdminDisputesPage
-- (reclamos de pago atados a un ride concreto).

-- ─── Hilos ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.support_threads (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              UUID        NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    status               TEXT        NOT NULL DEFAULT 'open'
                                     CHECK (status IN ('open','closed')),
    last_message_at      TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    last_message_preview TEXT,
    unread_for_user      BOOLEAN     NOT NULL DEFAULT false,
    unread_for_admin     BOOLEAN     NOT NULL DEFAULT false,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS idx_support_threads_open_recent
    ON public.support_threads (last_message_at DESC)
    WHERE status = 'open';

-- ─── Mensajes ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.support_messages (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id   BIGINT      NOT NULL REFERENCES public.support_threads(id) ON DELETE CASCADE,
    sender_id   UUID        NOT NULL REFERENCES auth.users(id),
    sender_role TEXT        NOT NULL CHECK (sender_role IN ('user','admin')),
    content     TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS idx_support_messages_thread
    ON public.support_messages (thread_id, created_at);

-- ─── Trigger: actualiza el hilo cuando entra un mensaje ─────────────
-- SECURITY DEFINER + search_path fijo (lección de migración 22).
CREATE OR REPLACE FUNCTION public.support_messages_after_insert()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    UPDATE public.support_threads
       SET last_message_at      = NEW.created_at,
           last_message_preview = LEFT(NEW.content, 80),
           unread_for_user      = CASE WHEN NEW.sender_role = 'admin' THEN true  ELSE unread_for_user  END,
           unread_for_admin     = CASE WHEN NEW.sender_role = 'user'  THEN true  ELSE unread_for_admin END
     WHERE id = NEW.thread_id;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_support_messages_after_insert ON public.support_messages;
CREATE TRIGGER trg_support_messages_after_insert
    AFTER INSERT ON public.support_messages
    FOR EACH ROW EXECUTE FUNCTION public.support_messages_after_insert();

-- ─── RLS ────────────────────────────────────────────────────────────
ALTER TABLE public.support_threads  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_messages ENABLE ROW LEVEL SECURITY;

-- threads.SELECT: dueño o admin
DROP POLICY IF EXISTS "support_threads_select" ON public.support_threads;
CREATE POLICY "support_threads_select"
    ON public.support_threads FOR SELECT TO authenticated
    USING (
        user_id = auth.uid()
        OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
    );

-- threads.INSERT: el dueño crea el suyo; admin puede crear para cualquiera
DROP POLICY IF EXISTS "support_threads_insert" ON public.support_threads;
CREATE POLICY "support_threads_insert"
    ON public.support_threads FOR INSERT TO authenticated
    WITH CHECK (
        user_id = auth.uid()
        OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
    );

-- threads.UPDATE: dueño (para apagar unread_for_user) o admin (cerrar, apagar unread_for_admin)
DROP POLICY IF EXISTS "support_threads_update" ON public.support_threads;
CREATE POLICY "support_threads_update"
    ON public.support_threads FOR UPDATE TO authenticated
    USING (
        user_id = auth.uid()
        OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
    );

-- messages.SELECT: participante del hilo (dueño o admin)
DROP POLICY IF EXISTS "support_messages_select" ON public.support_messages;
CREATE POLICY "support_messages_select"
    ON public.support_messages FOR SELECT TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.support_threads t
            WHERE t.id = support_messages.thread_id
              AND (
                  t.user_id = auth.uid()
                  OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
              )
        )
    );

-- messages.INSERT: sender_id debe ser uno mismo y coherente con el role
DROP POLICY IF EXISTS "support_messages_insert" ON public.support_messages;
CREATE POLICY "support_messages_insert"
    ON public.support_messages FOR INSERT TO authenticated
    WITH CHECK (
        sender_id = auth.uid()
        AND EXISTS (
            SELECT 1 FROM public.support_threads t
            WHERE t.id = support_messages.thread_id
              AND (
                  (sender_role = 'user'  AND t.user_id = auth.uid())
                  OR
                  (sender_role = 'admin' AND EXISTS (
                      SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin'
                  ))
              )
        )
    );

-- ─── Realtime ───────────────────────────────────────────────────────
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
          AND schemaname = 'public'
          AND tablename = 'support_threads'
    ) THEN
        EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.support_threads';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
          AND schemaname = 'public'
          AND tablename = 'support_messages'
    ) THEN
        EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.support_messages';
    END IF;
END $$;
