-- ============================================================
-- 36 · emergency_contacts — contactos de emergencia del usuario
-- ============================================================
-- Fase 9 paso D.P3 del roadmap (SOS contextual con geo).
--
-- Lista de contactos que el usuario quiere notificar al disparar SOS.
-- En MVP del feature SOS (v1) el endpoint solo emails a admin@higoapp.com
-- con la info del incidente, pero ya guardamos los contactos en DB para
-- que en v2 podamos:
--   - Listarlos en el email al admin (con click-to-call + wa.me)
--   - Disparar push si el contacto tiene la app instalada (matchear
--     por phone contra profiles.phone)
--   - Eventualmente SMS si se contrata Twilio (out of scope hoy)

CREATE TABLE IF NOT EXISTS public.emergency_contacts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name         TEXT        NOT NULL CHECK (length(trim(name)) > 0),
    phone        TEXT        NOT NULL CHECK (length(trim(phone)) > 0),
    relationship TEXT,        -- libre: "pareja", "madre", "amigo", etc.
    created_at   TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    UNIQUE (user_id, phone)   -- mismo contacto no se duplica
);

CREATE INDEX IF NOT EXISTS idx_emergency_contacts_user
    ON public.emergency_contacts (user_id);

ALTER TABLE public.emergency_contacts ENABLE ROW LEVEL SECURITY;

-- Solo el dueño puede leer / escribir sus contactos. Admins también
-- (para soporte / debugging de SOS).
DROP POLICY IF EXISTS "emergency_contacts_owner_all" ON public.emergency_contacts;
CREATE POLICY "emergency_contacts_owner_all"
    ON public.emergency_contacts FOR ALL TO authenticated
    USING      (user_id = auth.uid() OR public.is_admin(auth.uid()))
    WITH CHECK (user_id = auth.uid() OR public.is_admin(auth.uid()));
