-- ============================================================
-- 37 · sos_events — audit log de alertas de emergencia
-- ============================================================
-- Fase 9 paso D.P3 del roadmap.
--
-- Cada vez que un user (pasajero o conductor) dispara SOS desde
-- /api/send-emergency.php se inserta una fila acá. Permite:
--   - Métricas: SOS por mes, tasa de falsos positivos.
--   - Debugging post-incidente: qué pasó, dónde, qué ride, qué chofer.
--   - Workflow de resolución: admin marca resolved_at + nota cuando
--     contactó al usuario o al 911.

CREATE TABLE IF NOT EXISTS public.sos_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    ride_id         BIGINT      REFERENCES public.rides(id) ON DELETE SET NULL,
    -- Quién es la contraparte al momento del SOS. Si el SOS lo dispara
    -- el pasajero, contraparte = chofer; viceversa.
    counterpart_id  UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
    -- Rol del que disparó (para distinguir métricas pasajero vs chofer).
    triggered_by    TEXT        NOT NULL CHECK (triggered_by IN ('passenger','driver')),
    triggered_at    TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    -- Snapshot de la ubicación al momento del SOS (no es realtime).
    location_lat    NUMERIC,
    location_lng    NUMERIC,
    -- Metadata del incidente: snapshot del ride, datos del vehículo,
    -- contactos notificados, errores del email/push si los hubo.
    metadata        JSONB       NOT NULL DEFAULT '{}'::jsonb,
    -- Workflow de resolución (admin lo actualiza vía panel).
    resolved_at     TIMESTAMPTZ,
    resolved_by     UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
    resolved_note   TEXT
);

CREATE INDEX IF NOT EXISTS idx_sos_events_user_recent
    ON public.sos_events (user_id, triggered_at DESC);
CREATE INDEX IF NOT EXISTS idx_sos_events_unresolved
    ON public.sos_events (triggered_at DESC)
    WHERE resolved_at IS NULL;

ALTER TABLE public.sos_events ENABLE ROW LEVEL SECURITY;

-- El user que disparó el SOS puede leer sus propios eventos (para
-- historial / ver si fue resuelto). Admin lee y actualiza todos.
DROP POLICY IF EXISTS "sos_events_owner_read" ON public.sos_events;
CREATE POLICY "sos_events_owner_read"
    ON public.sos_events FOR SELECT TO authenticated
    USING (user_id = auth.uid() OR public.is_admin(auth.uid()));

-- INSERT vive en el endpoint PHP (service_role), pero por
-- consistencia: el dueño puede insertar sus propios eventos también
-- desde el frontend (fallback si el endpoint falla).
DROP POLICY IF EXISTS "sos_events_owner_insert" ON public.sos_events;
CREATE POLICY "sos_events_owner_insert"
    ON public.sos_events FOR INSERT TO authenticated
    WITH CHECK (user_id = auth.uid());

-- Solo admin marca como resuelto.
DROP POLICY IF EXISTS "sos_events_admin_update" ON public.sos_events;
CREATE POLICY "sos_events_admin_update"
    ON public.sos_events FOR UPDATE TO authenticated
    USING      (public.is_admin(auth.uid()))
    WITH CHECK (public.is_admin(auth.uid()));
