-- ============================================================
-- 41 · driver_documents — onboarding self-service del chofer
-- ============================================================
-- Fase 10 paso D.C1 del roadmap.
--
-- Hoy el flow es: admin registra manualmente al chofer en
-- AdminDriversPage (con upload de foto del vehículo + datos del
-- auto + welcome-driver.php que manda email de onboarding). No
-- escala: cada nuevo chofer pasa por la oficina o por un admin
-- humano leyendo papeles.
--
-- Con D.C1, el chofer se anota solo desde /driver/onboarding y
-- sube los 4 docs requeridos: cédula, licencia, RCV (seguro de
-- responsabilidad civil), foto del vehículo. Admin solo revisa y
-- aprueba/rechaza desde AdminDriversPage.
--
-- Una fila por (user_id, document_type). UNIQUE permite resubmit:
-- si el admin rechaza la cédula por borrosa, el chofer sube otra
-- foto y UPDATEa la misma fila (status vuelve a 'pending', se
-- limpia reviewed_at/by/rejection_reason).

CREATE TABLE IF NOT EXISTS public.driver_documents (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    -- Tipo de documento. Enum cerrado para garantizar consistencia con
    -- la UI y permitir agregar tipos nuevos en migrations futuras.
    document_type     TEXT        NOT NULL CHECK (document_type IN (
        'cedula',         -- documento de identidad (CI venezolana)
        'licencia',       -- licencia de conducir vigente
        'rcv',            -- póliza de responsabilidad civil del vehículo
        'vehicle_photo'   -- foto del vehículo (placa visible)
    )),
    -- Path al archivo en el bucket privado driver-docs (mig 42 lo crea).
    file_path         TEXT        NOT NULL,
    file_mime         TEXT,
    file_size         BIGINT,
    -- Workflow de revisión.
    status            TEXT        NOT NULL DEFAULT 'pending'
                                  CHECK (status IN ('pending', 'approved', 'rejected')),
    submitted_at      TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    reviewed_at       TIMESTAMPTZ,
    reviewed_by       UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
    rejection_reason  TEXT,
    UNIQUE (user_id, document_type)
);

CREATE INDEX IF NOT EXISTS idx_driver_documents_user
    ON public.driver_documents (user_id);
CREATE INDEX IF NOT EXISTS idx_driver_documents_pending
    ON public.driver_documents (submitted_at DESC)
    WHERE status = 'pending';

-- Trigger: al UPDATE de file_path (chofer resubmite), resetear el
-- workflow. Garantiza que un resubmit borra el rejection_reason
-- viejo y vuelve a pending automáticamente, sin que el frontend
-- tenga que recordar limpiar las 3 columnas.
CREATE OR REPLACE FUNCTION public.tg_driver_documents_resubmit()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.file_path IS DISTINCT FROM OLD.file_path THEN
        NEW.status           := 'pending';
        NEW.submitted_at     := timezone('utc', now());
        NEW.reviewed_at      := NULL;
        NEW.reviewed_by      := NULL;
        NEW.rejection_reason := NULL;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS driver_documents_resubmit ON public.driver_documents;
CREATE TRIGGER driver_documents_resubmit
    BEFORE UPDATE OF file_path ON public.driver_documents
    FOR EACH ROW
    EXECUTE FUNCTION public.tg_driver_documents_resubmit();

-- RLS:
ALTER TABLE public.driver_documents ENABLE ROW LEVEL SECURITY;

-- (1) El chofer ve sus propios docs (todos los status).
DROP POLICY IF EXISTS "driver_documents_owner_read" ON public.driver_documents;
CREATE POLICY "driver_documents_owner_read"
    ON public.driver_documents FOR SELECT TO authenticated
    USING (user_id = auth.uid() OR public.is_admin(auth.uid()));

-- (2) El chofer inserta/actualiza sus propios docs. status sigue
--     siendo 'pending' por default; los triggers de resubmit lo
--     resetean si cambia file_path. NO puede setear approved/rejected
--     desde el client (lo hace el admin vía policy aparte).
--     CHECK explícito en WITH CHECK: cuando el caller NO es admin,
--     status debe ser 'pending'.
DROP POLICY IF EXISTS "driver_documents_owner_write" ON public.driver_documents;
CREATE POLICY "driver_documents_owner_write"
    ON public.driver_documents FOR INSERT TO authenticated
    WITH CHECK (
        user_id = auth.uid()
        AND status = 'pending'
        AND reviewed_at IS NULL
        AND reviewed_by IS NULL
    );

DROP POLICY IF EXISTS "driver_documents_owner_update" ON public.driver_documents;
CREATE POLICY "driver_documents_owner_update"
    ON public.driver_documents FOR UPDATE TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (
        user_id = auth.uid()
        -- El owner solo puede UPDATEar el file_path/mime/size (resubmit).
        -- No puede tocar status/reviewed_*. El trigger se encarga de
        -- resetear status a pending al cambiar file_path.
        AND status = 'pending'
    );

-- (3) Admin UPDATEa el status + reviewed_at/by + rejection_reason.
DROP POLICY IF EXISTS "driver_documents_admin_update" ON public.driver_documents;
CREATE POLICY "driver_documents_admin_update"
    ON public.driver_documents FOR UPDATE TO authenticated
    USING      (public.is_admin(auth.uid()))
    WITH CHECK (public.is_admin(auth.uid()));

-- ─── Helper RPC: estado global de aprobación del chofer ─────────────
-- Devuelve true si el chofer tiene los 4 documents en status='approved'.
-- Lo usa el frontend de DriverDashboard como gate (no puede ponerse
-- online si retorna false).
CREATE OR REPLACE FUNCTION public.driver_is_fully_approved(p_uid UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
    SELECT COALESCE((
        SELECT COUNT(DISTINCT document_type) = 4
          FROM public.driver_documents
         WHERE user_id = p_uid
           AND status  = 'approved'
           AND document_type IN ('cedula', 'licencia', 'rcv', 'vehicle_photo')
    ), false);
$$;

REVOKE ALL ON FUNCTION public.driver_is_fully_approved(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.driver_is_fully_approved(UUID) TO authenticated;
