-- ============================================================
-- 43 · wallet_movements — audit log unificado de saldo HigoPay
-- ============================================================
-- Fase 11 paso D.A4 del roadmap.
--
-- Hoy Higo no tiene una tabla unificada de movimientos de saldo:
--   - driver_memberships     → pagos de membresía (driver → Higo).
--   - referral_credit_balance → contador acumulado en profiles
--     (driver). Sin historial de cómo llegó a ese número.
--   - payment_reports        → auditoría de pagos Banesco.
-- Cuando un admin quiere reembolsar a un pasajero por una disputa
-- ganada, no hay tabla donde anotar "Higo le debe $X al pasajero".
--
-- wallet_movements es el ledger único: una fila por evento de
-- crédito/débito. El balance del user se calcula como
-- SUM(amount) WHERE user_id = X (o más eficiente vía vista).
--
-- type controla qué representa cada movement:
--   refund_credit     → reembolso vía dispute (D.A4, este commit).
--   referral_credit   → bono por referir un user nuevo (Fase 15).
--   higopay_topup     → recarga manual de saldo (no usado hoy).
--   higopay_spend     → uso del saldo para pagar un ride (Fase 15).
--   membership_payment→ pago de membresía driver (mig 16 lo cubre
--                       hoy en driver_memberships; futuro: backfill).
--   manual_adjustment → admin ajusta saldo a mano con nota.

CREATE TABLE IF NOT EXISTS public.wallet_movements (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    type            TEXT        NOT NULL CHECK (type IN (
        'refund_credit',
        'referral_credit',
        'higopay_topup',
        'higopay_spend',
        'membership_payment',
        'manual_adjustment'
    )),
    -- amount con signo: + crédito (suma al saldo), - débito (resta).
    -- Numeric(12,2) cubre montos hasta ~9.999.999.999,99 USD.
    amount          NUMERIC(12, 2) NOT NULL CHECK (amount <> 0),
    currency        TEXT        NOT NULL DEFAULT 'USD',
    -- Referencias opcionales al evento que disparó el movement.
    -- Permite drill-down en panel admin sin denormalizar metadata.
    ref_ride_id     BIGINT      REFERENCES public.rides(id) ON DELETE SET NULL,
    ref_dispute_id  BIGINT,                -- placeholder para futuro disputes table
    note            TEXT,                  -- nota libre del admin
    created_by      UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS idx_wallet_movements_user
    ON public.wallet_movements (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_wallet_movements_ride
    ON public.wallet_movements (ref_ride_id) WHERE ref_ride_id IS NOT NULL;

-- Vista helper: balance neto por user (suma de amount).
-- SECURITY INVOKER por default — respeta RLS del SELECT del user.
CREATE OR REPLACE VIEW public.wallet_balances AS
SELECT
    user_id,
    SUM(amount)                    AS balance,
    COUNT(*)                       AS movements_count,
    MAX(created_at)                AS last_movement_at
FROM public.wallet_movements
GROUP BY user_id;

-- Grant SELECT en la vista (sin policy adicional — hereda la de
-- wallet_movements via security_invoker default).
GRANT SELECT ON public.wallet_balances TO authenticated;

-- ─── RLS ────────────────────────────────────────────────────────────
ALTER TABLE public.wallet_movements ENABLE ROW LEVEL SECURITY;

-- (1) El owner ve sus propios movements. Útil para que el pasajero
--     vea "Mis créditos" en una eventual /history o /wallet page.
DROP POLICY IF EXISTS "wallet_movements_owner_read" ON public.wallet_movements;
CREATE POLICY "wallet_movements_owner_read"
    ON public.wallet_movements FOR SELECT TO authenticated
    USING (user_id = auth.uid() OR public.is_admin(auth.uid()));

-- (2) Solo admins INSERT/UPDATE/DELETE. Los users NO pueden crear sus
--     propios movements desde el client (sería self-credit infinito).
--     Los movements se generan vía:
--       - Admin desde AdminDisputesPage (refund_credit).
--       - Triggers SQL futuros (credit_pending_referral RPC genera
--         referral_credit, etc).
DROP POLICY IF EXISTS "wallet_movements_admin_write" ON public.wallet_movements;
CREATE POLICY "wallet_movements_admin_write"
    ON public.wallet_movements FOR INSERT TO authenticated
    WITH CHECK (public.is_admin(auth.uid()));

DROP POLICY IF EXISTS "wallet_movements_admin_update" ON public.wallet_movements;
CREATE POLICY "wallet_movements_admin_update"
    ON public.wallet_movements FOR UPDATE TO authenticated
    USING      (public.is_admin(auth.uid()))
    WITH CHECK (public.is_admin(auth.uid()));

DROP POLICY IF EXISTS "wallet_movements_admin_delete" ON public.wallet_movements;
CREATE POLICY "wallet_movements_admin_delete"
    ON public.wallet_movements FOR DELETE TO authenticated
    USING (public.is_admin(auth.uid()));

-- ─── RPC: refund de una dispute ─────────────────────────────────────
-- Encapsula la operación "admin reembolsa al pasajero por una
-- disputa" en una sola RPC: valida admin, valida que el ride existe
-- y que el user_id del ride es el destinatario del crédito, inserta
-- el movement type='refund_credit' con la nota provista.
--
-- Garantiza atomicidad y reduce el riesgo de que el frontend mande
-- un INSERT con datos inconsistentes.
CREATE OR REPLACE FUNCTION public.admin_refund_ride(
    p_ride_id BIGINT,
    p_amount  NUMERIC,
    p_note    TEXT DEFAULT NULL
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_user_id     UUID;
    v_movement_id BIGINT;
BEGIN
    IF NOT public.is_admin(auth.uid()) THEN
        RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
    END IF;
    IF p_amount IS NULL OR p_amount <= 0 THEN
        RAISE EXCEPTION 'amount_must_be_positive' USING ERRCODE = '22023';
    END IF;
    SELECT user_id INTO v_user_id FROM public.rides WHERE id = p_ride_id;
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'ride_not_found' USING ERRCODE = '02000';
    END IF;

    INSERT INTO public.wallet_movements (
        user_id, type, amount, ref_ride_id, note, created_by
    ) VALUES (
        v_user_id, 'refund_credit', p_amount, p_ride_id, p_note, auth.uid()
    )
    RETURNING id INTO v_movement_id;

    RETURN v_movement_id;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_refund_ride(BIGINT, NUMERIC, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_refund_ride(BIGINT, NUMERIC, TEXT) TO authenticated;
