-- ============================================================
-- 45 · pricing_rules — surge pricing por zona/hora/día
-- ============================================================
-- Fase 11 paso D.A2 del roadmap.
--
-- Hoy `pricing_config` tiene una tarifa FIJA por vehicle_type
-- (base, per_km, delivery_fee, wait_per_min, stop_fee). Esta
-- migración suma una capa de "reglas activas" que aplican un
-- multiplicador sobre esa tarifa según contexto.
--
-- Ejemplos de uso:
--   - "Viernes 10pm a sábado 4am, todo carro x1.5" (noche con
--     demanda alta).
--   - "Domingos turistas 8am-8pm, camioneta x1.3" (mayor demanda
--     vs oferta).
--   - "Zona Higuerote centro, lunes-viernes 7-9am, moto x1.2"
--     (hora pico inter-ciudad).
--
-- El frontend (RequestRidePage) llama a get_active_pricing_multiplier
-- al calcular el precio y multiplica la tarifa base por el factor.

CREATE TABLE IF NOT EXISTS public.pricing_rules (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT        NOT NULL,
    -- Filtro vehicle_type. NULL = aplica a todos.
    vehicle_type    TEXT        CHECK (vehicle_type IS NULL OR vehicle_type IN ('moto', 'standard', 'van')),
    multiplier      NUMERIC(4, 2) NOT NULL CHECK (multiplier >= 0.5 AND multiplier <= 5.0),
    -- Filtro de día de semana. Array de 0..6 (0=domingo). NULL=todos.
    day_of_week     SMALLINT[],
    -- Filtro de hora. Rango [hour_start, hour_end) en horario local
    -- VE (UTC-4). NULL en ambos = todo el día. Si hour_start > hour_end
    -- el rango cruza medianoche (ej: start=22, end=4 = 10pm a 4am).
    hour_start      SMALLINT    CHECK (hour_start IS NULL OR (hour_start >= 0 AND hour_start < 24)),
    hour_end        SMALLINT    CHECK (hour_end IS NULL OR (hour_end >= 0 AND hour_end < 24)),
    -- Filtro de zona. NULL = todas las zonas. coverage_zones existe
    -- desde mig 20 (creo) — si no, dejamos NULL siempre.
    zone_id         BIGINT,
    -- Validity window. Para promos limitadas en el tiempo.
    starts_at       TIMESTAMPTZ,
    ends_at         TIMESTAMPTZ,
    active          BOOLEAN     NOT NULL DEFAULT true,
    note            TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    created_by      UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS idx_pricing_rules_active
    ON public.pricing_rules (active) WHERE active = true;

-- Trigger touch updated_at.
CREATE OR REPLACE FUNCTION public.tg_pricing_rules_touch()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := timezone('utc', now());
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS pricing_rules_touch ON public.pricing_rules;
CREATE TRIGGER pricing_rules_touch
    BEFORE UPDATE ON public.pricing_rules
    FOR EACH ROW EXECUTE FUNCTION public.tg_pricing_rules_touch();

-- RLS: lectura pública (los clientes necesitan calcular precio),
-- escritura solo admin.
ALTER TABLE public.pricing_rules ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "pricing_rules_read_all" ON public.pricing_rules;
CREATE POLICY "pricing_rules_read_all"
    ON public.pricing_rules FOR SELECT TO authenticated
    USING (true);

DROP POLICY IF EXISTS "pricing_rules_admin_write" ON public.pricing_rules;
CREATE POLICY "pricing_rules_admin_write"
    ON public.pricing_rules FOR ALL TO authenticated
    USING      (public.is_admin(auth.uid()))
    WITH CHECK (public.is_admin(auth.uid()));

-- ─── RPC: multiplier activo para un (vehicle_type, lat, lng, now) ──
-- Retorna el MÁXIMO multiplier de las reglas activas que matchean
-- el contexto. Si ninguna matchea, retorna 1.0 (no surge).
--
-- Matching:
--   - active = true
--   - vehicle_type NULL o = p_vehicle_type
--   - day_of_week NULL o contiene EXTRACT(dow FROM ahora_local)
--   - hora actual VE dentro de [hour_start, hour_end) — soporta
--     wrap medianoche.
--   - starts_at NULL o <= now
--   - ends_at NULL o > now
--   - zone_id NULL (lat/lng filter por zona queda para Fase 16)
CREATE OR REPLACE FUNCTION public.get_active_pricing_multiplier(
    p_vehicle_type TEXT,
    p_lat          NUMERIC DEFAULT NULL,
    p_lng          NUMERIC DEFAULT NULL
)
RETURNS NUMERIC
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_local  TIMESTAMPTZ := timezone('America/Caracas', now());
    v_hour   INT         := EXTRACT(HOUR FROM v_local);
    v_dow    INT         := EXTRACT(DOW  FROM v_local); -- 0=Sun..6=Sat
    v_mult   NUMERIC     := 1.0;
BEGIN
    SELECT COALESCE(MAX(multiplier), 1.0) INTO v_mult
      FROM public.pricing_rules
     WHERE active = true
       AND (vehicle_type IS NULL OR vehicle_type = p_vehicle_type)
       AND (day_of_week  IS NULL OR v_dow = ANY(day_of_week))
       AND (
           -- Sin filtro horario.
           (hour_start IS NULL AND hour_end IS NULL)
           OR
           -- Rango normal: [start, end).
           (hour_start IS NOT NULL AND hour_end IS NOT NULL
            AND hour_start <= hour_end
            AND v_hour >= hour_start AND v_hour < hour_end)
           OR
           -- Rango que cruza medianoche: [start, 24) U [0, end).
           (hour_start IS NOT NULL AND hour_end IS NOT NULL
            AND hour_start > hour_end
            AND (v_hour >= hour_start OR v_hour < hour_end))
       )
       AND (starts_at IS NULL OR starts_at <= now())
       AND (ends_at   IS NULL OR ends_at   >  now());
    RETURN COALESCE(v_mult, 1.0);
END;
$$;

REVOKE ALL ON FUNCTION public.get_active_pricing_multiplier(TEXT, NUMERIC, NUMERIC) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_active_pricing_multiplier(TEXT, NUMERIC, NUMERIC) TO authenticated;
