-- ============================================================
-- 46 · pricing_history — audit log de cambios en pricing_config
-- ============================================================
-- Fase 11 paso D.A2 del roadmap.
--
-- pricing_config (mig vieja) guarda la tarifa actual por
-- vehicle_type. Sin historial. Cuando alguien sube/baja una tarifa
-- no hay forma de saber qué tarifa estuvo activa en una fecha
-- pasada (importante para auditoría de viajes históricos y para
-- detectar cambios inesperados).
--
-- Solución: tabla append-only pricing_history + trigger AFTER
-- INSERT OR UPDATE en pricing_config que serializa la fila completa.

CREATE TABLE IF NOT EXISTS public.pricing_history (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_type  TEXT        NOT NULL,
    snapshot      JSONB       NOT NULL,
    changed_at    TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    changed_by    UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
    action        TEXT        NOT NULL CHECK (action IN ('INSERT', 'UPDATE'))
);

CREATE INDEX IF NOT EXISTS idx_pricing_history_vehicle
    ON public.pricing_history (vehicle_type, changed_at DESC);

-- Trigger: captura row completo en JSONB después de cualquier
-- INSERT o UPDATE en pricing_config.
CREATE OR REPLACE FUNCTION public.tg_pricing_history_capture()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    INSERT INTO public.pricing_history (vehicle_type, snapshot, changed_by, action)
    VALUES (
        NEW.vehicle_type,
        to_jsonb(NEW),
        auth.uid(),
        TG_OP
    );
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS pricing_history_capture ON public.pricing_config;
CREATE TRIGGER pricing_history_capture
    AFTER INSERT OR UPDATE ON public.pricing_config
    FOR EACH ROW
    EXECUTE FUNCTION public.tg_pricing_history_capture();

-- RLS: solo admin lee el historial.
ALTER TABLE public.pricing_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "pricing_history_admin_read" ON public.pricing_history;
CREATE POLICY "pricing_history_admin_read"
    ON public.pricing_history FOR SELECT TO authenticated
    USING (public.is_admin(auth.uid()));

-- INSERT vive solo en el trigger (SECURITY DEFINER). No policy
-- INSERT para authenticated — nadie escribe acá manualmente.

-- ─── Backfill: snapshot inicial de cada fila actual ───────────────
-- Para que el primer cambio post-migración tenga un baseline para
-- comparar contra. Si la tabla pricing_config está vacía, no hace
-- nada. Idempotencia: solo inserta si pricing_history aún no tiene
-- baseline para ese vehicle_type.
INSERT INTO public.pricing_history (vehicle_type, snapshot, action)
SELECT pc.vehicle_type, to_jsonb(pc), 'INSERT'
  FROM public.pricing_config pc
 WHERE NOT EXISTS (
     SELECT 1 FROM public.pricing_history ph
      WHERE ph.vehicle_type = pc.vehicle_type
 );
