-- ====================================================================
-- 70 · Higo Shop Store Memberships Migration
-- ====================================================================
-- This migration implements the table, indexes, and RLS policies 
-- for the $30 USD monthly Store Membership system for Higo Shop merchants.

BEGIN;

-- ====================================================================
-- 1. CREATE STORE MEMBERSHIPS TABLE
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.store_memberships (
  id bigint generated by default as identity primary key,
  store_id uuid not null references public.stores(id) on delete cascade,
  amount numeric not null default 30.00 check (amount >= 0),
  payment_method text not null check (payment_method in ('cash', 'pago_movil', 'zelle')),
  reference text, -- Pago Móvil Banesco or transaction reference
  status text not null default 'active' check (status in ('active', 'expired', 'refunded')),
  paid_at timestamptz not null default now(),
  expires_at timestamptz not null,
  notes text,
  created_at timestamptz default now()
);

-- Indexing for speed
CREATE INDEX IF NOT EXISTS idx_store_memberships_store
  ON public.store_memberships(store_id, expires_at desc);
CREATE INDEX IF NOT EXISTS idx_store_memberships_active
  ON public.store_memberships(expires_at)
  WHERE status = 'active';

-- Enable RLS
ALTER TABLE public.store_memberships ENABLE ROW LEVEL SECURITY;

-- ====================================================================
-- 2. RLS POLICIES FOR STORE MEMBERSHIPS
-- ====================================================================

-- 1. Store owners (merchants) can read their own store memberships
DROP POLICY IF EXISTS "Allow store owners to read memberships" ON public.store_memberships;
CREATE POLICY "Allow store owners to read memberships"
  ON public.store_memberships FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.stores s
      WHERE s.id = store_id AND s.owner_id = auth.uid()
    )
  );

-- 2. Platform Admins can manage all memberships
DROP POLICY IF EXISTS "Allow admins to manage memberships" ON public.store_memberships;
CREATE POLICY "Allow admins to manage memberships"
  ON public.store_memberships FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- ====================================================================
-- 3. HELPER FUNCTION: check if a store has an active membership
-- ====================================================================
CREATE OR REPLACE FUNCTION public.store_has_active_membership(p_store_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.store_memberships
    WHERE store_id = p_store_id
      AND status = 'active'
      AND expires_at > now()
  );
$$;

GRANT EXECUTE ON FUNCTION public.store_has_active_membership(uuid) TO authenticated;

COMMIT;
