-- Higo admin redesign: membership-first finance, audit, permissions and aggregated metrics.
-- Safe rollout: MFA enforcement defaults OFF until all admins enroll a verified factor.

begin;

create extension if not exists pgcrypto;

create table if not exists public.driver_membership_plans (
    id uuid primary key default gen_random_uuid(),
    code text not null unique,
    name text not null,
    vehicle_type text,
    period text not null check (period in ('weekly','monthly','yearly')),
    duration_days integer not null check (duration_days > 0),
    amount numeric(12,2) not null check (amount >= 0),
    currency text not null default 'USD',
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

insert into public.driver_membership_plans (code, name, vehicle_type, period, duration_days, amount)
values
    ('moto-weekly', 'Moto semanal', 'moto', 'weekly', 7, 3),
    ('moto-monthly', 'Moto mensual', 'moto', 'monthly', 30, 10),
    ('car-weekly', 'Carro semanal', 'standard', 'weekly', 7, 5),
    ('car-monthly', 'Carro mensual', 'standard', 'monthly', 30, 20),
    ('van-weekly', 'Camioneta semanal', 'van', 'weekly', 7, 7),
    ('van-monthly', 'Camioneta mensual', 'van', 'monthly', 30, 25)
on conflict (code) do nothing;

create table if not exists public.driver_memberships (
    id bigint generated by default as identity primary key,
    driver_id uuid not null references public.profiles(id) on delete restrict,
    plan text,
    amount numeric(12,2) not null default 0,
    period text,
    paid_at timestamptz not null default now(),
    expires_at timestamptz not null,
    status text not null default 'active'
);

alter table public.driver_memberships
    add column if not exists plan_id uuid references public.driver_membership_plans(id),
    add column if not exists currency text not null default 'USD',
    add column if not exists payment_method text,
    add column if not exists payment_reference text,
    add column if not exists notes text,
    add column if not exists receipt_url text,
    add column if not exists created_by uuid,
    add column if not exists voided_at timestamptz,
    add column if not exists voided_by uuid,
    add column if not exists void_reason text,
    add column if not exists updated_at timestamptz not null default now();

alter table public.profiles
    add column if not exists archived_at timestamptz,
    add column if not exists archived_by uuid,
    add column if not exists archive_reason text,
    add column if not exists suspension_reason text,
    add column if not exists subscription_override_until timestamptz;

create index if not exists idx_driver_memberships_driver_expires
    on public.driver_memberships(driver_id, expires_at desc)
    where voided_at is null;
create index if not exists idx_driver_memberships_paid_at
    on public.driver_memberships(paid_at desc)
    where voided_at is null;
create unique index if not exists idx_driver_memberships_payment_reference
    on public.driver_memberships(payment_reference)
    where payment_reference is not null and voided_at is null;

create table if not exists public.admin_staff_roles (
    user_id uuid primary key references public.profiles(id) on delete cascade,
    staff_role text not null default 'viewer'
        check (staff_role in ('super_admin','operations','support','finance','viewer')),
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    updated_by uuid
);

insert into public.admin_staff_roles (user_id, staff_role)
select id, 'super_admin'
from public.profiles
where role = 'admin'
on conflict (user_id) do nothing;

create table if not exists public.admin_security_settings (
    singleton boolean primary key default true check (singleton),
    require_mfa boolean not null default false,
    session_minutes integer not null default 60 check (session_minutes between 15 and 720),
    updated_at timestamptz not null default now(),
    updated_by uuid
);
insert into public.admin_security_settings(singleton) values (true)
on conflict (singleton) do nothing;

create table if not exists public.admin_audit_log (
    id bigint generated by default as identity primary key,
    actor_id uuid,
    action text not null,
    entity_type text not null,
    entity_id text,
    before_data jsonb,
    after_data jsonb,
    reason text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);
create index if not exists idx_admin_audit_log_created_at on public.admin_audit_log(created_at desc);
create index if not exists idx_admin_audit_log_entity on public.admin_audit_log(entity_type, entity_id);

create or replace function public.higo_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1 from public.profiles p
        where p.id = auth.uid() and p.role = 'admin'
    );
$$;

create or replace function public.higo_admin_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
    select coalesce((
        select r.staff_role
        from public.admin_staff_roles r
        where r.user_id = auth.uid() and r.active
    ), case when public.higo_is_admin() then 'viewer' else null end);
$$;

create or replace function public.higo_admin_can(p_permission text)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
    v_role text := public.higo_admin_role();
begin
    if v_role is null then return false; end if;
    if v_role = 'super_admin' then return true; end if;
    if p_permission in ('view_dashboard','view_analytics') then return true; end if;
    if v_role = 'operations' and p_permission in ('manage_drivers','manage_operations','manage_pricing','manage_zones','manage_disputes') then return true; end if;
    if v_role = 'support' and p_permission in ('manage_support','manage_disputes','view_users') then return true; end if;
    if v_role = 'finance' and p_permission in ('manage_memberships','view_finance','manage_disputes') then return true; end if;
    if v_role = 'viewer' and p_permission in ('view_users') then return true; end if;
    return false;
end;
$$;

create or replace function public.higo_assert_admin(p_permission text, p_sensitive boolean default false)
returns void
language plpgsql
stable
security definer
set search_path = public
as $$
declare
    v_require_mfa boolean := false;
    v_aal text := coalesce(auth.jwt()->>'aal', 'aal1');
begin
    if not public.higo_admin_can(p_permission) then
        raise exception 'admin_permission_denied' using errcode = '42501';
    end if;
    select require_mfa into v_require_mfa from public.admin_security_settings where singleton;
    if p_sensitive and v_require_mfa and v_aal <> 'aal2' then
        raise exception 'admin_mfa_required' using errcode = '42501';
    end if;
end;
$$;

create or replace function public.admin_get_context()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
    v_role text;
    v_require_mfa boolean;
begin
    if not public.higo_is_admin() then
        return jsonb_build_object('authorized', false);
    end if;
    v_role := public.higo_admin_role();
    select require_mfa into v_require_mfa from public.admin_security_settings where singleton;
    return jsonb_build_object(
        'authorized', true,
        'user_id', auth.uid(),
        'staff_role', v_role,
        'require_mfa', coalesce(v_require_mfa, false),
        'aal', coalesce(auth.jwt()->>'aal', 'aal1'),
        'permissions', jsonb_build_object(
            'manage_memberships', public.higo_admin_can('manage_memberships'),
            'manage_drivers', public.higo_admin_can('manage_drivers'),
            'manage_support', public.higo_admin_can('manage_support'),
            'manage_operations', public.higo_admin_can('manage_operations'),
            'manage_users', v_role = 'super_admin',
            'manage_security', v_role = 'super_admin'
        )
    );
end;
$$;

create or replace function public.higo_membership_status(
    p_expires_at timestamptz,
    p_membership_status text,
    p_archived_at timestamptz,
    p_suspended_at timestamptz,
    p_override_until timestamptz
)
returns text
language sql
stable
as $$
    select case
        when p_archived_at is not null then 'archived'
        when p_suspended_at is not null then 'suspended'
        when p_override_until is not null and p_override_until >= now() then 'grace_period'
        when p_membership_status is null then 'no_membership'
        when p_membership_status <> 'active' then p_membership_status
        when p_expires_at < now() then 'expired'
        when p_expires_at <= now() + interval '7 days' then 'expiring_soon'
        else 'active'
    end;
$$;

create or replace view public.admin_driver_membership_status as
select
    p.id,
    p.full_name,
    p.phone,
    p.email,
    p.avatar_url,
    p.vehicle_type,
    p.vehicle_brand,
    p.vehicle_model,
    p.vehicle_color,
    p.license_plate,
    p.status as online_status,
    p.updated_at as location_updated_at,
    p.subscription_status,
    p.last_payment_date,
    p.suspended_at,
    p.suspension_reason,
    p.archived_at,
    p.archive_reason,
    p.subscription_override_until,
    p.created_at,
    m.id as membership_id,
    m.plan_id,
    coalesce(mp.name, m.plan) as membership_plan,
    m.amount as membership_amount,
    m.currency,
    m.period,
    m.paid_at,
    m.expires_at,
    m.payment_method,
    m.payment_reference,
    public.higo_membership_status(
        m.expires_at, m.status, p.archived_at, p.suspended_at, p.subscription_override_until
    ) as membership_state
from public.profiles p
left join lateral (
    select dm.*
    from public.driver_memberships dm
    where dm.driver_id = p.id and dm.voided_at is null
    order by dm.expires_at desc, dm.paid_at desc
    limit 1
) m on true
left join public.driver_membership_plans mp on mp.id = m.plan_id
where p.role = 'driver';

create or replace function public.admin_dashboard_metrics()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
    v_today timestamptz := date_trunc('day', now());
    v_month timestamptz := date_trunc('month', now());
    v_result jsonb;
begin
    perform public.higo_assert_admin('view_dashboard');
    select jsonb_build_object(
        'membershipRevenueToday', coalesce((select sum(amount) from public.driver_memberships where voided_at is null and paid_at >= v_today), 0),
        'membershipRevenueMonth', coalesce((select sum(amount) from public.driver_memberships where voided_at is null and paid_at >= v_month), 0),
        'activeMemberships', (select count(*) from public.admin_driver_membership_status where membership_state in ('active','expiring_soon','grace_period')),
        'expiredMemberships', (select count(*) from public.admin_driver_membership_status where membership_state in ('expired','no_membership')),
        'expiringSoon', (select count(*) from public.admin_driver_membership_status where membership_state = 'expiring_soon'),
        'driversOnline', (select count(*) from public.profiles where role='driver' and status='online' and updated_at > now() - interval '90 seconds'),
        'ridesToday', (select count(*) from public.rides where created_at >= v_today),
        'tripVolumeToday', coalesce((select sum(price) from public.rides where created_at >= v_today and payment_confirmed_at is not null), 0),
        'openDisputes', (select count(*) from public.rides where payment_confirmed_at is null and (payment_reference is not null or payment_confirmed_by_user or payment_confirmed_by_driver)),
        'supportUnread', coalesce((select count(*) from public.support_threads where status='open' and unread_for_admin), 0),
        'activeWithoutMembership', (select count(*) from public.admin_driver_membership_status where subscription_status='active' and membership_state in ('expired','no_membership','suspended','archived')),
        'subsidyCostMonth', 0,
        'generatedAt', now()
    ) into v_result;
    return v_result;
end;
$$;

create or replace function public.admin_business_analytics(
    p_days integer default 30
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
    v_days integer := greatest(7, least(coalesce(p_days, 30), 365));
    v_since timestamptz;
    v_revenue numeric := 0;
    v_payers bigint := 0;
    v_payments bigint := 0;
    v_renewing bigint := 0;
    v_membership_daily jsonb := '[]'::jsonb;
    v_trip_daily jsonb := '[]'::jsonb;
begin
    v_since := date_trunc('day', now()) - (v_days - 1) * interval '1 day';

    perform public.higo_assert_admin('view_analytics');

    select
        coalesce(sum(amount), 0),
        count(*),
        count(distinct driver_id)
    into
        v_revenue,
        v_payments,
        v_payers
    from public.driver_memberships
    where voided_at is null
      and paid_at >= v_since;

    select count(*)
    into v_renewing
    from (
        select driver_id
        from public.driver_memberships
        where voided_at is null
          and paid_at >= v_since
        group by driver_id
        having count(*) > 1
    ) as renewing_drivers;

    select coalesce(
        jsonb_agg(
            jsonb_build_object(
                'day', gs.bucket_day::date,
                'revenue', coalesce(md.revenue, 0),
                'payments', coalesce(md.payments, 0)
            )
            order by gs.bucket_day
        ),
        '[]'::jsonb
    )
    into v_membership_daily
    from generate_series(
        v_since,
        date_trunc('day', now()),
        interval '1 day'
    ) as gs(bucket_day)
    left join (
        select
            date_trunc('day', paid_at) as bucket_day,
            sum(amount) as revenue,
            count(*) as payments
        from public.driver_memberships
        where voided_at is null
          and paid_at >= v_since
        group by date_trunc('day', paid_at)
    ) as md
        on md.bucket_day = gs.bucket_day;

    select coalesce(
        jsonb_agg(
            jsonb_build_object(
                'day', gs.bucket_day::date,
                'volume', coalesce(td.volume, 0),
                'rides', coalesce(td.rides, 0)
            )
            order by gs.bucket_day
        ),
        '[]'::jsonb
    )
    into v_trip_daily
    from generate_series(
        v_since,
        date_trunc('day', now()),
        interval '1 day'
    ) as gs(bucket_day)
    left join (
        select
            date_trunc('day', created_at) as bucket_day,
            sum(
                case
                    when payment_confirmed_at is not null then price
                    else 0
                end
            ) as volume,
            count(*) as rides
        from public.rides
        where created_at >= v_since
        group by date_trunc('day', created_at)
    ) as td
        on td.bucket_day = gs.bucket_day;

    return jsonb_build_object(
        'days', v_days,
        'membershipRevenue', v_revenue,
        'payments', v_payments,
        'payingDrivers', v_payers,
        'averageRevenuePerDriver',
            case when v_payers > 0 then round(v_revenue / v_payers, 2) else 0 end,
        'renewalRate',
            case when v_payers > 0 then round((v_renewing::numeric / v_payers::numeric) * 100, 1) else 0 end,
        'activeMemberships',
            (
                select count(*)
                from public.admin_driver_membership_status
                where membership_state in ('active','expiring_soon','grace_period')
            ),
        'tripVolume',
            coalesce(
                (
                    select sum(price)
                    from public.rides
                    where created_at >= v_since
                      and payment_confirmed_at is not null
                ),
                0
            ),
        'rides',
            (
                select count(*)
                from public.rides
                where created_at >= v_since
            ),
        'membershipDaily', v_membership_daily,
        'tripDaily', v_trip_daily,
        'generatedAt', now()
    );
end;
$$;

create or replace function public.admin_list_drivers(
    p_query text default null,
    p_state text default 'all',
    p_limit integer default 50,
    p_offset integer default 0
)
returns setof public.admin_driver_membership_status
language plpgsql
stable
security definer
set search_path = public
as $$
begin
    perform public.higo_assert_admin('view_dashboard');
    return query
    select * from public.admin_driver_membership_status d
    where (coalesce(trim(p_query),'') = '' or
           d.full_name ilike '%' || trim(p_query) || '%' or
           d.phone ilike '%' || trim(p_query) || '%' or
           d.license_plate ilike '%' || trim(p_query) || '%' or
           d.payment_reference ilike '%' || trim(p_query) || '%')
      and (p_state = 'all' or d.membership_state = p_state)
    order by
        case d.membership_state when 'expired' then 1 when 'no_membership' then 2 when 'expiring_soon' then 3 else 4 end,
        d.expires_at nulls first,
        d.created_at desc
    limit greatest(1, least(coalesce(p_limit,50),200))
    offset greatest(coalesce(p_offset,0),0);
end;
$$;

create or replace function public.higo_sync_driver_membership(p_driver_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_active boolean;
    v_last_payment timestamptz;
begin
    select exists(
        select 1 from public.driver_memberships
        where driver_id = p_driver_id and voided_at is null and status='active' and expires_at >= now()
    ), max(paid_at) filter (where voided_at is null)
    into v_active, v_last_payment
    from public.driver_memberships where driver_id = p_driver_id;

    update public.profiles
       set subscription_status = case when v_active then 'active' else 'suspended' end,
           last_payment_date = v_last_payment
     where id = p_driver_id and role='driver';
end;
$$;

create or replace function public.admin_record_driver_membership(
    p_driver_id uuid,
    p_plan_id uuid,
    p_payment_method text,
    p_payment_reference text default null,
    p_notes text default null,
    p_amount numeric default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_plan public.driver_membership_plans%rowtype;
    v_id bigint;
    v_start timestamptz := now();
    v_expires timestamptz;
begin
    perform public.higo_assert_admin('manage_memberships', true);
    select * into v_plan from public.driver_membership_plans where id=p_plan_id and active;
    if not found then raise exception 'membership_plan_not_found'; end if;
    if not exists(select 1 from public.profiles where id=p_driver_id and role='driver' and archived_at is null) then
        raise exception 'driver_not_found_or_archived';
    end if;
    v_expires := v_start + make_interval(days => v_plan.duration_days);
    insert into public.driver_memberships(
        driver_id, plan_id, plan, amount, currency, period, paid_at, expires_at,
        status, payment_method, payment_reference, notes, created_by
    ) values (
        p_driver_id, v_plan.id, v_plan.code, coalesce(p_amount, v_plan.amount), v_plan.currency,
        v_plan.period, v_start, v_expires, 'active', nullif(trim(p_payment_method),''),
        nullif(trim(p_payment_reference),''), nullif(trim(p_notes),''), auth.uid()
    ) returning id into v_id;
    perform public.higo_sync_driver_membership(p_driver_id);
    insert into public.admin_audit_log(actor_id, action, entity_type, entity_id, after_data)
    values(auth.uid(),'membership.record','driver_membership',v_id::text,
        jsonb_build_object('driver_id',p_driver_id,'plan_id',p_plan_id,'amount',coalesce(p_amount,v_plan.amount),'expires_at',v_expires));
    return v_id;
end;
$$;

create or replace function public.admin_void_driver_membership(p_membership_id bigint, p_reason text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_driver uuid;
    v_before jsonb;
begin
    perform public.higo_assert_admin('manage_memberships', true);
    if coalesce(trim(p_reason),'') = '' then raise exception 'void_reason_required'; end if;
    select driver_id, to_jsonb(dm) into v_driver, v_before
      from public.driver_memberships dm where id=p_membership_id and voided_at is null for update;
    if v_driver is null then raise exception 'membership_not_found'; end if;
    update public.driver_memberships
       set status='voided', voided_at=now(), voided_by=auth.uid(), void_reason=trim(p_reason), updated_at=now()
     where id=p_membership_id;
    perform public.higo_sync_driver_membership(v_driver);
    insert into public.admin_audit_log(actor_id, action, entity_type, entity_id, before_data, reason)
    values(auth.uid(),'membership.void','driver_membership',p_membership_id::text,v_before,trim(p_reason));
end;
$$;

create or replace function public.admin_set_driver_exception(
    p_driver_id uuid,
    p_action text,
    p_reason text,
    p_until timestamptz default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_before jsonb;
begin
    perform public.higo_assert_admin('manage_drivers', true);
    if coalesce(trim(p_reason),'')='' then raise exception 'reason_required'; end if;
    select to_jsonb(p) into v_before from public.profiles p where id=p_driver_id and role='driver' for update;
    if v_before is null then raise exception 'driver_not_found'; end if;
    if p_action='suspend' then
        update public.profiles set subscription_status='suspended', suspended_at=now(), suspension_reason=trim(p_reason) where id=p_driver_id;
    elsif p_action='grace' then
        if p_until is null or p_until <= now() then raise exception 'future_until_required'; end if;
        update public.profiles set subscription_override_until=p_until, suspended_at=null, suspension_reason=null where id=p_driver_id;
    elsif p_action='clear' then
        update public.profiles set subscription_override_until=null, suspended_at=null, suspension_reason=null where id=p_driver_id;
        perform public.higo_sync_driver_membership(p_driver_id);
    else
        raise exception 'invalid_driver_action';
    end if;
    insert into public.admin_audit_log(actor_id, action, entity_type, entity_id, before_data, after_data, reason)
    select auth.uid(),'driver.'||p_action,'profile',p_driver_id::text,v_before,to_jsonb(p),trim(p_reason)
      from public.profiles p where p.id=p_driver_id;
end;
$$;

create or replace function public.admin_archive_driver(p_driver_id uuid, p_reason text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_before jsonb;
begin
    perform public.higo_assert_admin('manage_drivers', true);
    if coalesce(trim(p_reason),'')='' then raise exception 'archive_reason_required'; end if;
    select to_jsonb(p) into v_before from public.profiles p where id=p_driver_id and role='driver' for update;
    if v_before is null then raise exception 'driver_not_found'; end if;
    update public.profiles set archived_at=now(), archived_by=auth.uid(), archive_reason=trim(p_reason), status='offline', subscription_status='suspended' where id=p_driver_id;
    insert into public.admin_audit_log(actor_id, action, entity_type, entity_id, before_data, after_data, reason)
    select auth.uid(),'driver.archive','profile',p_driver_id::text,v_before,to_jsonb(p),trim(p_reason) from public.profiles p where p.id=p_driver_id;
end;
$$;

create or replace function public.admin_list_staff()
returns table(user_id uuid, full_name text, phone text, staff_role text, active boolean, updated_at timestamptz)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
    perform public.higo_assert_admin('view_users');
    return query
    select p.id, p.full_name, p.phone, coalesce(r.staff_role,'viewer'), coalesce(r.active,true), r.updated_at
    from public.profiles p left join public.admin_staff_roles r on r.user_id=p.id
    where p.role='admin' order by p.full_name nulls last;
end;
$$;

create or replace function public.admin_update_staff_role(p_user_id uuid, p_staff_role text, p_active boolean default true)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    perform public.higo_assert_admin('manage_users', true);
    if public.higo_admin_role() <> 'super_admin' then raise exception 'super_admin_required'; end if;
    if p_staff_role not in ('super_admin','operations','support','finance','viewer') then raise exception 'invalid_staff_role'; end if;
    if p_user_id=auth.uid() and (p_staff_role<>'super_admin' or not p_active) then raise exception 'cannot_demote_self'; end if;
    insert into public.admin_staff_roles(user_id,staff_role,active,updated_by)
    values(p_user_id,p_staff_role,p_active,auth.uid())
    on conflict(user_id) do update set staff_role=excluded.staff_role, active=excluded.active, updated_at=now(), updated_by=auth.uid();
    insert into public.admin_audit_log(actor_id,action,entity_type,entity_id,after_data)
    values(auth.uid(),'admin.staff_role','admin_staff_role',p_user_id::text,jsonb_build_object('staff_role',p_staff_role,'active',p_active));
end;
$$;

create or replace function public.admin_set_security_settings(p_require_mfa boolean, p_session_minutes integer default 60)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    perform public.higo_assert_admin('manage_users', true);
    if public.higo_admin_role()<>'super_admin' then raise exception 'super_admin_required'; end if;
    update public.admin_security_settings
       set require_mfa=p_require_mfa,
           session_minutes=greatest(15,least(coalesce(p_session_minutes,60),720)),
           updated_at=now(), updated_by=auth.uid()
     where singleton;
    insert into public.admin_audit_log(actor_id,action,entity_type,entity_id,after_data)
    values(auth.uid(),'admin.security_settings','admin_security_settings','singleton',jsonb_build_object('require_mfa',p_require_mfa,'session_minutes',p_session_minutes));
end;
$$;

create or replace function public.admin_change_profile_role(p_user_id uuid, p_role text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_before jsonb;
begin
    perform public.higo_assert_admin('manage_users', true);
    if public.higo_admin_role()<>'super_admin' then raise exception 'super_admin_required'; end if;
    if p_role not in ('passenger','user','driver','admin','merchant') then raise exception 'invalid_profile_role'; end if;
    if p_user_id=auth.uid() and p_role<>'admin' then raise exception 'cannot_demote_self'; end if;
    select to_jsonb(p) into v_before from public.profiles p where id=p_user_id for update;
    update public.profiles set role=p_role where id=p_user_id;
    if p_role='admin' then
        insert into public.admin_staff_roles(user_id,staff_role) values(p_user_id,'viewer') on conflict(user_id) do nothing;
    end if;
    insert into public.admin_audit_log(actor_id,action,entity_type,entity_id,before_data,after_data)
    select auth.uid(),'profile.role_change','profile',p_user_id::text,v_before,to_jsonb(p) from public.profiles p where p.id=p_user_id;
end;
$$;

create or replace function public.higo_audit_row()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    v_before jsonb := case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) else null end;
    v_after jsonb := case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) else null end;
    v_id text := coalesce(v_after->>'id', v_before->>'id', v_after->>'user_id', v_before->>'user_id');
begin
    if auth.uid() is not null then
        insert into public.admin_audit_log(actor_id,action,entity_type,entity_id,before_data,after_data,metadata)
        values(auth.uid(),lower(tg_op),tg_table_name,v_id,v_before,v_after,jsonb_build_object('schema',tg_table_schema));
    end if;
    return coalesce(new,old);
end;
$$;

do $$
declare t text;
begin
    foreach t in array array['pricing_config','pricing_rules','promo_codes','coverage_zones'] loop
        if to_regclass('public.'||t) is not null then
            execute format('drop trigger if exists trg_higo_audit_%I on public.%I',t,t);
            execute format('create trigger trg_higo_audit_%I after insert or update or delete on public.%I for each row execute function public.higo_audit_row()',t,t);
        end if;
    end loop;
end $$;

alter table public.driver_membership_plans enable row level security;
alter table public.admin_staff_roles enable row level security;
alter table public.admin_security_settings enable row level security;
alter table public.admin_audit_log enable row level security;

drop policy if exists admin_read_membership_plans on public.driver_membership_plans;
create policy admin_read_membership_plans on public.driver_membership_plans for select using (public.higo_is_admin());
drop policy if exists admin_manage_membership_plans on public.driver_membership_plans;
create policy admin_manage_membership_plans on public.driver_membership_plans for all using (public.higo_admin_role()='super_admin') with check (public.higo_admin_role()='super_admin');

drop policy if exists admin_read_staff_roles on public.admin_staff_roles;
create policy admin_read_staff_roles on public.admin_staff_roles for select using (public.higo_is_admin());
drop policy if exists admin_read_security_settings on public.admin_security_settings;
create policy admin_read_security_settings on public.admin_security_settings for select using (public.higo_is_admin());
drop policy if exists admin_read_audit_log on public.admin_audit_log;
create policy admin_read_audit_log on public.admin_audit_log for select using (public.higo_is_admin());

grant select on public.admin_driver_membership_status to authenticated;
grant execute on function public.admin_get_context() to authenticated;
grant execute on function public.admin_dashboard_metrics() to authenticated;
grant execute on function public.admin_business_analytics(integer) to authenticated;
grant execute on function public.admin_list_drivers(text,text,integer,integer) to authenticated;
grant execute on function public.admin_record_driver_membership(uuid,uuid,text,text,text,numeric) to authenticated;
grant execute on function public.admin_void_driver_membership(bigint,text) to authenticated;
grant execute on function public.admin_set_driver_exception(uuid,text,text,timestamptz) to authenticated;
grant execute on function public.admin_archive_driver(uuid,text) to authenticated;
grant execute on function public.admin_list_staff() to authenticated;
grant execute on function public.admin_update_staff_role(uuid,text,boolean) to authenticated;
grant execute on function public.admin_set_security_settings(boolean,integer) to authenticated;
grant execute on function public.admin_change_profile_role(uuid,text) to authenticated;

commit;
