-- First-party operational events for funnel/reliability analysis.
-- No raw coordinates, bank payloads, passwords or free-form PII are accepted.

begin;

create table if not exists public.platform_events (
    id bigint generated by default as identity primary key,
    user_id uuid references public.profiles(id) on delete set null,
    session_id text,
    event_name text not null,
    route text,
    entity_type text,
    entity_id text,
    properties jsonb not null default '{}'::jsonb,
    app_version text,
    platform text,
    created_at timestamptz not null default now(),
    constraint platform_events_name_format
        check (event_name ~ '^[a-z0-9][a-z0-9._-]{1,79}$'),
    constraint platform_events_properties_size
        check (octet_length(properties::text) <= 8192)
);

create index if not exists idx_platform_events_created
    on public.platform_events(created_at desc);
create index if not exists idx_platform_events_name_created
    on public.platform_events(event_name, created_at desc);
create index if not exists idx_platform_events_entity
    on public.platform_events(entity_type, entity_id, created_at desc);

alter table public.platform_events enable row level security;

drop policy if exists platform_events_admin_read on public.platform_events;
create policy platform_events_admin_read
on public.platform_events for select
using (public.higo_is_admin());

revoke insert, update, delete on public.platform_events from anon, authenticated;
grant select on public.platform_events to authenticated;

create or replace function public.track_platform_event(
    p_event_name text,
    p_route text default null,
    p_entity_type text default null,
    p_entity_id text default null,
    p_properties jsonb default '{}'::jsonb,
    p_session_id text default null,
    p_app_version text default null,
    p_platform text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_id bigint;
    v_properties jsonb := coalesce(p_properties, '{}'::jsonb);
begin
    if coalesce(trim(p_event_name), '') !~ '^[a-z0-9][a-z0-9._-]{1,79}$' then
        raise exception 'invalid_event_name';
    end if;
    if jsonb_typeof(v_properties) <> 'object' then
        raise exception 'event_properties_must_be_object';
    end if;
    if octet_length(v_properties::text) > 8192 then
        raise exception 'event_properties_too_large';
    end if;

    -- Defense in depth: remove known sensitive keys even if a caller sends
    -- them accidentally. Values such as coordinates and bank raw responses
    -- are never useful in the analytics table.
    v_properties := v_properties
        - 'password'
        - 'token'
        - 'access_token'
        - 'refresh_token'
        - 'raw_response'
        - 'pickup_lat'
        - 'pickup_lng'
        - 'dropoff_lat'
        - 'dropoff_lng'
        - 'phone'
        - 'email';

    insert into public.platform_events(
        user_id,
        session_id,
        event_name,
        route,
        entity_type,
        entity_id,
        properties,
        app_version,
        platform
    ) values (
        auth.uid(),
        left(nullif(trim(p_session_id), ''), 100),
        trim(p_event_name),
        left(nullif(trim(p_route), ''), 200),
        left(nullif(trim(p_entity_type), ''), 80),
        left(nullif(trim(p_entity_id), ''), 160),
        v_properties,
        left(nullif(trim(p_app_version), ''), 40),
        left(nullif(trim(p_platform), ''), 80)
    ) returning id into v_id;

    return v_id;
end;
$$;

grant execute on function public.track_platform_event(
    text,text,text,text,jsonb,text,text,text
) to anon, authenticated;

create or replace function public.admin_platform_funnel(p_days integer default 30)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
    v_days integer := greatest(1, least(coalesce(p_days, 30), 365));
    v_since timestamptz;
begin
    perform public.higo_assert_admin('view_analytics');
    v_since := now() - make_interval(days => v_days);

    return jsonb_build_object(
        'days', v_days,
        'rideRequestStarted', (
            select count(*) from public.platform_events
            where event_name = 'ride.request_started' and created_at >= v_since
        ),
        'rideRequested', (
            select count(*) from public.platform_events
            where event_name = 'ride.requested' and created_at >= v_since
        ),
        'rideAccepted', (
            select count(*) from public.ride_state_events
            where to_status = 'accepted' and created_at >= v_since
        ),
        'rideCompleted', (
            select count(*) from public.ride_state_events
            where to_status = 'completed' and created_at >= v_since
        ),
        'rideCancelled', (
            select count(*) from public.ride_state_events
            where to_status = 'cancelled' and created_at >= v_since
        ),
        'membershipCheckoutViewed', (
            select count(*) from public.platform_events
            where event_name = 'membership.checkout_viewed' and created_at >= v_since
        ),
        'membershipPaymentValidated', (
            select count(*) from public.platform_events
            where event_name = 'membership.payment_validated' and created_at >= v_since
        ),
        'medianAcceptSeconds', (
            select percentile_cont(0.5) within group (
                order by extract(epoch from (r.accepted_at - r.created_at))
            )
            from public.rides r
            where r.accepted_at is not null
              and r.created_at >= v_since
        ),
        'generatedAt', now()
    );
end;
$$;

grant execute on function public.admin_platform_funnel(integer) to authenticated;

-- Optional retention when pg_cron is available. The DO block is safe on
-- projects without the extension.
do $$
begin
    if exists(select 1 from pg_extension where extname = 'pg_cron') then
        if not exists(select 1 from cron.job where jobname = 'platform_events_purge_180d') then
            perform cron.schedule(
                'platform_events_purge_180d',
                '25 4 * * *',
                $job$delete from public.platform_events where created_at < now() - interval '180 days'$job$
            );
        end if;
    end if;
exception
    when undefined_table or insufficient_privilege then null;
end $$;

commit;
