-- Directed ride offers reduce global Realtime fan-out. The current rides
-- channel remains available during rollout; drivers switch to this table only
-- after staging/device tests enable the feature flag.

begin;

create table if not exists public.ride_offers (
    id bigint generated by default as identity primary key,
    ride_id bigint not null references public.rides(id) on delete cascade,
    driver_id uuid not null references public.profiles(id) on delete cascade,
    status text not null default 'offered'
        check (status in ('offered','accepted','expired','withdrawn')),
    distance_km numeric(10,3),
    score numeric(12,4) not null default 0,
    offered_at timestamptz not null default now(),
    expires_at timestamptz not null default now() + interval '3 minutes',
    responded_at timestamptz,
    unique (ride_id, driver_id)
);

create index if not exists idx_ride_offers_driver_active
    on public.ride_offers(driver_id, expires_at desc)
    where status = 'offered';
create index if not exists idx_ride_offers_ride
    on public.ride_offers(ride_id, status);

alter table public.ride_offers enable row level security;

drop policy if exists ride_offers_driver_read on public.ride_offers;
create policy ride_offers_driver_read
on public.ride_offers for select
using (driver_id = auth.uid() or public.higo_is_admin());

revoke insert, update, delete on public.ride_offers from anon, authenticated;
grant select on public.ride_offers to authenticated;

create or replace function public.higo_dispatch_ride(
    p_ride_id bigint,
    p_limit integer default 20,
    p_radius_km numeric default 30
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    v_ride public.rides%rowtype;
    v_count integer := 0;
    v_limit integer := greatest(1, least(coalesce(p_limit, 20), 100));
    v_radius numeric := greatest(1, least(coalesce(p_radius_km, 30), 100));
begin
    select * into v_ride
    from public.rides r
    where r.id = p_ride_id
      and r.status = 'requested';

    if not found or v_ride.pickup_lat is null or v_ride.pickup_lng is null then
        return 0;
    end if;

    insert into public.ride_offers(
        ride_id, driver_id, distance_km, score, expires_at
    )
    select
        v_ride.id,
        candidates.driver_id,
        candidates.distance_km,
        -- Prefer proximity, then recently updated GPS.
        round((100 - least(candidates.distance_km, 100))
            + greatest(0, 10 - candidates.location_age_minutes), 4),
        now() + interval '3 minutes'
    from (
        select
            p.id as driver_id,
            public.higo_haversine_km(
                p.curr_lat::double precision,
                p.curr_lng::double precision,
                v_ride.pickup_lat::double precision,
                v_ride.pickup_lng::double precision
            ) as distance_km,
            extract(epoch from (now() - coalesce(p.last_location_update, p.updated_at))) / 60
                as location_age_minutes
        from public.profiles p
        where p.role = 'driver'
          and p.status = 'online'
          and p.archived_at is null
          and p.suspended_at is null
          and p.curr_lat is not null
          and p.curr_lng is not null
          and coalesce(p.last_location_update, p.updated_at) >= now() - interval '3 minutes'
          and public.higo_canonical_vehicle_type(p.vehicle_type)
              = public.higo_canonical_vehicle_type(v_ride.ride_type)
          and (
              exists (
                  select 1
                  from public.driver_memberships dm
                  where dm.driver_id = p.id
                    and dm.voided_at is null
                    and dm.status = 'active'
                    and dm.expires_at >= now()
              )
              or (
                  p.subscription_override_until is not null
                  and p.subscription_override_until >= now()
              )
          )
    ) candidates
    where candidates.distance_km <= v_radius
    order by candidates.distance_km, candidates.location_age_minutes
    limit v_limit
    on conflict (ride_id, driver_id) do update
    set status = case
            when public.ride_offers.status = 'accepted' then 'accepted'
            else 'offered'
        end,
        distance_km = excluded.distance_km,
        score = excluded.score,
        offered_at = now(),
        expires_at = excluded.expires_at;

    get diagnostics v_count = row_count;
    return v_count;
end;
$$;

create or replace function public.driver_list_ride_offers(
    p_limit integer default 20
)
returns table(
    offer_id bigint,
    expires_at timestamptz,
    distance_km numeric,
    score numeric,
    ride jsonb
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
    perform public.higo_assert_driver_operational();

    return query
    select
        o.id,
        o.expires_at,
        o.distance_km,
        o.score,
        to_jsonb(r)
    from public.ride_offers o
    join public.rides r on r.id = o.ride_id
    where o.driver_id = auth.uid()
      and o.status = 'offered'
      and o.expires_at > now()
      and r.status = 'requested'
      and r.driver_id is null
    order by o.score desc, o.offered_at desc
    limit greatest(1, least(coalesce(p_limit, 20), 50));
end;
$$;

grant execute on function public.driver_list_ride_offers(integer) to authenticated;
revoke all on function public.higo_dispatch_ride(bigint,integer,numeric)
from public, anon, authenticated;
grant execute on function public.higo_dispatch_ride(bigint,integer,numeric)
to service_role;

create or replace function public.higo_dispatch_new_ride()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if new.status = 'requested' then
        perform public.higo_dispatch_ride(new.id, 20, 30);
    end if;
    return new;
end;
$$;

drop trigger if exists trg_higo_dispatch_new_ride on public.rides;
create trigger trg_higo_dispatch_new_ride
after insert on public.rides
for each row
execute function public.higo_dispatch_new_ride();

create or replace function public.higo_sync_ride_offer_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if new.status = 'accepted' and new.driver_id is not null then
        update public.ride_offers
        set status = case when driver_id = new.driver_id then 'accepted' else 'withdrawn' end,
            responded_at = case when driver_id = new.driver_id then now() else responded_at end
        where ride_id = new.id
          and status = 'offered';
    elsif new.status in ('cancelled','completed') then
        update public.ride_offers
        set status = case when status = 'accepted' then status else 'withdrawn' end
        where ride_id = new.id
          and status = 'offered';
    end if;
    return new;
end;
$$;

drop trigger if exists trg_higo_sync_ride_offer_status on public.rides;
create trigger trg_higo_sync_ride_offer_status
after update of status, driver_id on public.rides
for each row
execute function public.higo_sync_ride_offer_status();

commit;
