-- Centralized Higo Driver application workflow.
-- Public submissions are ingested server-to-server; only authorized admins can read PII.

begin;

create extension if not exists pgcrypto;

create table if not exists public.driver_applications (
    id uuid primary key default gen_random_uuid(),
    application_code text not null unique
        check (application_code ~ '^HD-[0-9]{8}-[A-F0-9]{8}$'),
    idempotency_hash text not null unique,
    full_name text not null,
    cedula text not null,
    phone text not null,
    phone_digits text not null,
    email text not null,
    email_hash text not null,
    city text not null,
    vehicle_type text not null check (vehicle_type in ('moto','carro','camioneta')),
    vehicle_brand text not null,
    vehicle_model text not null,
    vehicle_year integer,
    vehicle_color text not null,
    license_plate text not null,
    license_plate_hash text not null,
    status text not null default 'pending_delivery'
        check (status in (
            'pending_delivery','delivery_failed','received','under_review',
            'documents_requested','documents_submitted','correction_requested',
            'approved','converted','waitlist','rejected'
        )),
    status_reason text,
    admin_notes text,
    terms_version text not null,
    privacy_version text not null,
    accept_terms boolean not null default false,
    accept_privacy boolean not null default false,
    accept_contact boolean not null default false,
    source text not null default 'higodriver.com',
    submitted_ip_hash text,
    confirmation_email_sent boolean not null default false,
    converted_user_id uuid references public.profiles(id) on delete set null,
    converted_at timestamptz,
    last_status_changed_at timestamptz not null default now(),
    last_status_changed_by uuid,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_driver_applications_status_created
    on public.driver_applications(status, created_at desc);
create index if not exists idx_driver_applications_email
    on public.driver_applications(lower(email));
create index if not exists idx_driver_applications_vehicle_city
    on public.driver_applications(vehicle_type, city);

create table if not exists public.driver_application_documents (
    id uuid primary key default gen_random_uuid(),
    application_id uuid not null references public.driver_applications(id) on delete cascade,
    document_type text not null check (document_type in (
        'identity','driver_license','vehicle_registration','rcv',
        'vehicle_photo','health_certificate','payment_details','other'
    )),
    file_name text not null,
    mime_type text not null,
    size_bytes bigint not null check (size_bytes > 0 and size_bytes <= 8388608),
    storage_path text not null unique,
    review_status text not null default 'pending'
        check (review_status in ('pending','approved','rejected')),
    review_notes text,
    reviewed_by uuid,
    reviewed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_driver_application_documents_application
    on public.driver_application_documents(application_id, created_at);

create table if not exists public.driver_application_upload_tokens (
    id uuid primary key default gen_random_uuid(),
    application_id uuid not null references public.driver_applications(id) on delete cascade,
    token_hash text not null unique,
    expires_at timestamptz not null,
    used_at timestamptz,
    last_used_at timestamptz,
    created_by uuid,
    created_at timestamptz not null default now()
);

create index if not exists idx_driver_application_upload_tokens_application
    on public.driver_application_upload_tokens(application_id, expires_at desc);

create table if not exists public.driver_application_events (
    id bigint generated by default as identity primary key,
    application_id uuid not null references public.driver_applications(id) on delete cascade,
    actor_type text not null check (actor_type in ('system','admin','applicant')),
    actor_id uuid,
    event_type text not null,
    from_status text,
    to_status text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_driver_application_events_application
    on public.driver_application_events(application_id, created_at desc);

create or replace function public.higo_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at := now();
    return new;
end;
$$;

drop trigger if exists trg_driver_applications_touch on public.driver_applications;
create trigger trg_driver_applications_touch
before update on public.driver_applications
for each row execute function public.higo_touch_updated_at();

drop trigger if exists trg_driver_application_documents_touch on public.driver_application_documents;
create trigger trg_driver_application_documents_touch
before update on public.driver_application_documents
for each row execute function public.higo_touch_updated_at();

alter table public.driver_applications enable row level security;
alter table public.driver_application_documents enable row level security;
alter table public.driver_application_upload_tokens enable row level security;
alter table public.driver_application_events enable row level security;

drop policy if exists driver_applications_admin_select on public.driver_applications;
create policy driver_applications_admin_select
on public.driver_applications for select to authenticated
using (public.higo_admin_can('manage_drivers'));

drop policy if exists driver_applications_admin_update on public.driver_applications;
create policy driver_applications_admin_update
on public.driver_applications for update to authenticated
using (public.higo_admin_can('manage_drivers'))
with check (public.higo_admin_can('manage_drivers'));

drop policy if exists driver_application_documents_admin_select on public.driver_application_documents;
create policy driver_application_documents_admin_select
on public.driver_application_documents for select to authenticated
using (public.higo_admin_can('manage_drivers'));

drop policy if exists driver_application_documents_admin_update on public.driver_application_documents;
create policy driver_application_documents_admin_update
on public.driver_application_documents for update to authenticated
using (public.higo_admin_can('manage_drivers'))
with check (public.higo_admin_can('manage_drivers'));

drop policy if exists driver_application_events_admin_select on public.driver_application_events;
create policy driver_application_events_admin_select
on public.driver_application_events for select to authenticated
using (public.higo_admin_can('manage_drivers'));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'driver-applications',
    'driver-applications',
    false,
    8388608,
    array['image/jpeg','image/png','image/webp','application/pdf']
)
on conflict (id) do update set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists driver_application_storage_admin_read on storage.objects;
create policy driver_application_storage_admin_read
on storage.objects for select to authenticated
using (
    bucket_id = 'driver-applications'
    and public.higo_admin_can('manage_drivers')
);

create or replace function public.higo_driver_application_transition_allowed(
    p_from text,
    p_to text
)
returns boolean
language sql
immutable
as $$
    select p_from = p_to or case p_from
        when 'pending_delivery' then p_to in ('received','delivery_failed')
        when 'delivery_failed' then p_to in ('received','rejected')
        when 'received' then p_to in ('under_review','documents_requested','waitlist','rejected')
        when 'under_review' then p_to in ('documents_requested','approved','waitlist','rejected')
        when 'documents_requested' then p_to in ('documents_submitted','correction_requested','rejected')
        when 'documents_submitted' then p_to in ('correction_requested','approved','rejected')
        when 'correction_requested' then p_to in ('documents_submitted','documents_requested','rejected')
        when 'approved' then p_to in ('converted','rejected')
        when 'waitlist' then p_to in ('under_review','rejected')
        else false
    end;
$$;

create or replace function public.admin_list_driver_applications(
    p_query text default null,
    p_status text default 'all',
    p_limit integer default 50,
    p_offset integer default 0
)
returns table (
    application_code text,
    full_name text,
    email text,
    phone text,
    city text,
    vehicle_type text,
    vehicle_brand text,
    vehicle_model text,
    license_plate text,
    status text,
    documents_count bigint,
    pending_documents_count bigint,
    created_at timestamptz,
    updated_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
    perform public.higo_assert_admin('manage_drivers');
    return query
    select
        a.application_code,
        a.full_name,
        a.email,
        a.phone,
        a.city,
        a.vehicle_type,
        a.vehicle_brand,
        a.vehicle_model,
        a.license_plate,
        a.status,
        count(d.id) as documents_count,
        count(d.id) filter (where d.review_status = 'pending') as pending_documents_count,
        a.created_at,
        a.updated_at
    from public.driver_applications a
    left join public.driver_application_documents d on d.application_id = a.id
    where (coalesce(p_status, 'all') = 'all' or a.status = p_status)
      and (
        coalesce(trim(p_query), '') = ''
        or a.application_code ilike '%' || trim(p_query) || '%'
        or a.full_name ilike '%' || trim(p_query) || '%'
        or a.email ilike '%' || trim(p_query) || '%'
        or a.phone ilike '%' || trim(p_query) || '%'
        or a.license_plate ilike '%' || trim(p_query) || '%'
      )
    group by a.id
    order by a.created_at desc
    limit greatest(1, least(coalesce(p_limit, 50), 100))
    offset greatest(coalesce(p_offset, 0), 0);
end;
$$;

create or replace function public.admin_get_driver_application(p_application_code text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
    v_application public.driver_applications%rowtype;
    v_documents jsonb;
    v_events jsonb;
begin
    perform public.higo_assert_admin('manage_drivers');

    select * into v_application
    from public.driver_applications
    where application_code = upper(trim(p_application_code));

    if not found then
        return null;
    end if;

    select coalesce(jsonb_agg(to_jsonb(d) order by d.created_at), '[]'::jsonb)
      into v_documents
      from public.driver_application_documents d
     where d.application_id = v_application.id;

    select coalesce(jsonb_agg(to_jsonb(e) order by e.created_at desc), '[]'::jsonb)
      into v_events
      from (
          select * from public.driver_application_events
          where application_id = v_application.id
          order by created_at desc
          limit 100
      ) e;

    return to_jsonb(v_application)
        || jsonb_build_object('documents', v_documents, 'events', v_events);
end;
$$;

create or replace function public.admin_set_driver_application_status(
    p_application_code text,
    p_status text,
    p_reason text default null,
    p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_before public.driver_applications%rowtype;
    v_after public.driver_applications%rowtype;
begin
    perform public.higo_assert_admin('manage_drivers', true);

    select * into v_before
    from public.driver_applications
    where application_code = upper(trim(p_application_code))
    for update;

    if not found then
        raise exception 'driver_application_not_found' using errcode = 'P0002';
    end if;

    if not public.higo_driver_application_transition_allowed(v_before.status, p_status) then
        raise exception 'invalid_driver_application_transition:%->%', v_before.status, p_status
            using errcode = '22023';
    end if;

    update public.driver_applications
       set status = p_status,
           status_reason = nullif(trim(coalesce(p_reason, '')), ''),
           last_status_changed_at = now(),
           last_status_changed_by = auth.uid()
     where id = v_before.id
     returning * into v_after;

    insert into public.driver_application_events(
        application_id, actor_type, actor_id, event_type, from_status, to_status, metadata
    ) values (
        v_before.id, 'admin', auth.uid(), 'status_changed', v_before.status, v_after.status,
        coalesce(p_metadata, '{}'::jsonb) || jsonb_build_object('reason', p_reason)
    );

    insert into public.admin_audit_log(
        actor_id, action, entity_type, entity_id, before_data, after_data, reason, metadata
    ) values (
        auth.uid(), 'driver_application.status_change', 'driver_application', v_before.application_code,
        jsonb_build_object('status', v_before.status),
        jsonb_build_object('status', v_after.status),
        p_reason,
        coalesce(p_metadata, '{}'::jsonb)
    );

    return to_jsonb(v_after);
end;
$$;

create or replace function public.admin_review_driver_application_document(
    p_document_id uuid,
    p_review_status text,
    p_notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_before public.driver_application_documents%rowtype;
    v_after public.driver_application_documents%rowtype;
begin
    perform public.higo_assert_admin('manage_drivers', true);
    if p_review_status not in ('approved','rejected') then
        raise exception 'invalid_document_review_status' using errcode = '22023';
    end if;

    select * into v_before
      from public.driver_application_documents
     where id = p_document_id
     for update;
    if not found then
        raise exception 'driver_application_document_not_found' using errcode = 'P0002';
    end if;

    update public.driver_application_documents
       set review_status = p_review_status,
           review_notes = nullif(trim(coalesce(p_notes, '')), ''),
           reviewed_by = auth.uid(),
           reviewed_at = now()
     where id = p_document_id
     returning * into v_after;

    insert into public.driver_application_events(
        application_id, actor_type, actor_id, event_type, metadata
    ) values (
        v_before.application_id, 'admin', auth.uid(), 'document_reviewed',
        jsonb_build_object(
            'document_id', v_before.id,
            'document_type', v_before.document_type,
            'review_status', p_review_status,
            'notes', p_notes
        )
    );

    return to_jsonb(v_after);
end;
$$;

create or replace function public.higo_public_driver_application_status(
    p_application_code text,
    p_email text
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
    v_application public.driver_applications%rowtype;
    v_label text;
    v_next_step text;
begin
    select * into v_application
      from public.driver_applications
     where application_code = upper(trim(p_application_code))
       and lower(email) = lower(trim(p_email));

    if not found then return null; end if;

    select
        case v_application.status
            when 'pending_delivery' then 'Solicitud en proceso'
            when 'delivery_failed' then 'Pendiente de confirmación'
            when 'received' then 'Solicitud recibida'
            when 'under_review' then 'En revisión'
            when 'documents_requested' then 'Documentos solicitados'
            when 'documents_submitted' then 'Documentos recibidos'
            when 'correction_requested' then 'Corrección solicitada'
            when 'approved' then 'Solicitud aprobada'
            when 'converted' then 'Registro completado'
            when 'waitlist' then 'En lista de espera'
            when 'rejected' then 'Solicitud no aprobada'
            else 'Solicitud recibida'
        end,
        case v_application.status
            when 'pending_delivery' then 'Estamos confirmando la recepción de tu solicitud.'
            when 'delivery_failed' then 'El equipo debe verificar manualmente la recepción.'
            when 'received' then 'El equipo Higo realizará la revisión inicial y te indicará el siguiente paso.'
            when 'under_review' then 'Estamos validando cobertura, datos y capacidad operativa.'
            when 'documents_requested' then 'Revisa tu correo y completa la carga segura de requisitos.'
            when 'documents_submitted' then 'Tus documentos fueron recibidos y están pendientes de revisión.'
            when 'correction_requested' then 'Revisa el correo del equipo Higo y corrige los documentos indicados.'
            when 'approved' then 'Tu solicitud fue aprobada. El equipo completará la creación de tu cuenta.'
            when 'converted' then 'Tu cuenta Higo Driver fue creada. Revisa tu correo para ingresar.'
            when 'waitlist' then 'Tu zona o modalidad está temporalmente sin cupo.'
            when 'rejected' then 'La solicitud no cumple actualmente los criterios de incorporación.'
            else 'El equipo Higo revisará tu solicitud.'
        end
      into v_label, v_next_step;

    return jsonb_build_object(
        'application_id', v_application.application_code,
        'status', v_application.status,
        'status_label', v_label,
        'next_step', v_next_step,
        'updated_at', v_application.updated_at
    );
end;
$$;

revoke all on function public.admin_list_driver_applications(text,text,integer,integer) from public, anon;
revoke all on function public.admin_get_driver_application(text) from public, anon;
revoke all on function public.admin_set_driver_application_status(text,text,text,jsonb) from public, anon;
revoke all on function public.admin_review_driver_application_document(uuid,text,text) from public, anon;
grant execute on function public.admin_list_driver_applications(text,text,integer,integer) to authenticated;
grant execute on function public.admin_get_driver_application(text) to authenticated;
grant execute on function public.admin_set_driver_application_status(text,text,text,jsonb) to authenticated;
grant execute on function public.admin_review_driver_application_document(uuid,text,text) to authenticated;

revoke all on function public.higo_public_driver_application_status(text,text) from public;
grant execute on function public.higo_public_driver_application_status(text,text) to anon, authenticated;

commit;
